Replace with enum two strings that were in strings.xml but were used as
commons-app/apps-android-commons pull request #2939
Opened 2019-05-06 16:13 UTC by kateOmally

constants. Remove strings from strings.xml Issue # 2931

**Description (required)**
Two strings in strings.xml were being used as constants. Therefore, did not need to be strings, much less translatable strings, so changed to an enum and removed strings from strings.xml.

Fixes #2931 Remove the strings which have to be stored as constant from strings.xml

What changes did you make and why?
defined an enum, ReviewController.DelteReason, and removed strings from strings.xml.

**Tests performed (required)**
ReviewHelperTest
DeleteHelperTest
Ran app through the IDE on an Android device running 8.0.0. Used the Review feature.

Tested {build variant, e.g. ProdDebug} on {name of device or emulator} with API level {API level}.
Tested betaDebug on HTC U Ultra phone with API level 26.

**Screenshots showing what changed (optional - for UI changes)**
No UI changes.

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._
yep.

2019-05-07 20:54 UTC, neslihanturan requested changes

2019-05-07 20:54 UTC, neslihanturan commented on app/src/main/java/fr/free/nrw/commons/delete/DeleteHelper.java
> +        if (problem == ReviewController.DeleteReason.SPAM) {
Why don't use equals?

2019-05-08 15:17 UTC, kateOmally commented
If you like, I will change it to .equals().   If there's a convention for
using .equals instead of ==, i must have missed it. Please point me to the
right resource.

Correct me if I'm wrong:  I thank that as an enum, Java can use use either
== or .equals(). They're the same except that == provides compile time type
checking which .equals doesn't.

On Tue, May 7, 2019 at 1:54 PM neslihanturan <notifications@github.com>
wrote:

> *@neslihanturan* requested changes on this pull request.
> ------------------------------
>
> In app/src/main/java/fr/free/nrw/commons/delete/DeleteHelper.java
> <https://github.com/commons-app/apps-android-commons/pull/2939#discussion_r281824931>
> :
>
> > @@ -152,12 +153,12 @@ public void askReasonAndExecute(Media media, Context context, String question, S
>          String[] reasonList = {"Reason 1", "Reason 2", "Reason 3", "Reason 4"};
>
>
> -        if (problem.equals("spam")) {
> +        if (problem == ReviewController.DeleteReason.SPAM) {
>
> Why don't use equals?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/commons-app/apps-android-commons/pull/2939#pullrequestreview-234755579>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALLQB36MAW4A4ECKYU6W6W3PUHUBRANCNFSM4HLBM3NA>
> .
>

2019-05-08 15:29 UTC, ashishkumar468 commented
@kateOmally There is no convention regarding the usage of == or .equals. Its just that,  == operators for reference comparison (address comparison) and .equals() method for content comparison. As far as I understand (and I may be wrong), in this scenario, we do not need address comparison as well right ?

2019-05-08 15:40 UTC, kateOmally commented
For strings, yes, but for enums, I believe the .equals() method just calls
the == operator

https://www.geeksforgeeks.org/comparing-enum-members-java/

I don't think it's that important either way. I thought == was more clear
because  it makes clear that we're not using a String. But in this case,
there's no danger of ambiguity, so it can go either way. Do you want me to
change it?


On Wed, May 8, 2019 at 8:29 AM Ashish Kumar <notifications@github.com>
wrote:

> @kateOmally <https://github.com/kateOmally> There is no convention
> regarding the usage of == or .equals. Its just that, == operators for
> reference comparison (address comparison) and .equals() method for content
> comparison. As far as I understand (and I may be wrong), in this scenario,
> we do not need address comparison as well right ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/commons-app/apps-android-commons/pull/2939#issuecomment-490533590>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALLQB3ZIPYXIO3WUDAA7FTTPULWURANCNFSM4HLBM3NA>
> .
>

2019-05-08 15:47 UTC, ashishkumar468 commented
@kateOmally Thank you for reminding me, for the case of enums,  .equals(), it simply defers to ==. Actually == would be better as it is null safe as well. Concluding from this, IMO, the current state is good and you need not make any changes.

2019-05-08 15:48 UTC, ashishkumar468 approved these changes

2019-05-08 18:37 UTC, neslihanturan commented
After reading this https://stackoverflow.com/questions/1750435/comparing-java-enum-members-or-equals seems like there is several opinions on this. My concern was about reference comparing, but since you explained this is not the case and @ashishkumar468 approved it, this PR fine for me too. Thanks for your first time contribution @kateOmally :tada:

2019-05-08 18:37 UTC, neslihanturan approved these changes

2019-05-08 18:37 UTC, merged