With changed for limited connection mode
commons-app/apps-android-commons pull request #3934
Opened 2020-09-22 10:27 UTC by maskaravivek

**Description (required)**

Fixes #746

2020-09-23 06:05 UTC, ashishkumar468 approved these changes

2020-09-24 15:02 UTC, misaochan requested changes
Hi @maskaravivek , thanks for the PR. I tested it with Nexus 5X emulator API 28. The auto-resume feature works well in general. :) Just a few issues:


-  Could you use the image provided by Neslihan at https://github.com/commons-app/apps-android-commons/issues/746#issuecomment-694342210 as the placeholder for images when limited connection mode is enabled? Currently just a white background is displayed.
- The "upload started!" toast is still displayed when an upload is initiated in limited connection mode. This should be changed to "Upload queued (limited connection mode enabled)".
- **Important:** My upload automatically starts as soon as I disabled limited connection mode, but after the progress bar has moved a bit, it displays an "app not responding" dialog and then crashes when I choose to close the app. This is 100% reproducible for me regardless of what image I use. When I start the app up again, it displays the contribution as "Failed", and the upload does not succeed. For some reason the stack trace for the crash is not displayed on logcat despite  being on debug setting. This line `fr.free.nrw.commons I/ree.nrw.common: Wrote stack traces to '[tombstoned]'` might have something to do with it.


Logcat:

```
2020-09-25 00:59:56.346 13934-13984/fr.free.nrw.commons D/CookieManager: Domain:commons.wikimedia.org
2020-09-25 00:59:56.874 13934-13984/fr.free.nrw.commons D/OkHttp: <-- 200 https://commons.wikimedia.org/w/api.php?format=json&action=wbgetentities&props=labels&languagefallback=1&ids=M73015382%7CM73015420%7CM73088561%7CM73089533%7CM73089562%7CM73089999%7CM73090180%7CM73094093%7CM73094191%7CM73094360 (529ms, unknown-length body)
2020-09-25 00:59:56.931 13934-13979/fr.free.nrw.commons D/OkHttp: --> GET https://commons.wikimedia.org/w/api.php?action=query&format=json&formatversion=2&generator=allimages&gaisort=timestamp&gaidir=older&prop=imageinfo&iiprop=url|extmetadata&iiurlwidth=640&iiextmetadatafilter=DateTime|Categories|GPSLatitude|GPSLongitude|ImageDescription|DateTimeOriginal|Artist|LicenseShortName|LicenseUrl&gaiuser=Misaochan2&gailimit=10&gaicontinue=20180909144956|Breakfast_at_Brisbane_cafe.jpg&continue=gaicontinue||
2020-09-25 00:59:56.933 13934-13979/fr.free.nrw.commons D/CookieManager: Domain:commons.wikimedia.org
2020-09-25 00:59:57.675 13934-13979/fr.free.nrw.commons D/OkHttp: <-- 200 https://commons.wikimedia.org/w/api.php?action=query&format=json&formatversion=2&generator=allimages&gaisort=timestamp&gaidir=older&prop=imageinfo&iiprop=url|extmetadata&iiurlwidth=640&iiextmetadatafilter=DateTime|Categories|GPSLatitude|GPSLongitude|ImageDescription|DateTimeOriginal|Artist|LicenseShortName|LicenseUrl&gaiuser=Misaochan2&gailimit=10&gaicontinue=20180909144956|Breakfast_at_Brisbane_cafe.jpg&continue=gaicontinue|| (744ms, unknown-length body)
2020-09-25 00:59:57.678 13934-13979/fr.free.nrw.commons D/OkHttp: --> GET https://commons.wikimedia.org/w/api.php?format=json&action=wbgetentities&props=labels&languagefallback=1&ids=M72352190%7CM72352313%7CM72435047%7CM72458952%7CM72459084%7CM72462685%7CM72587723%7CM72587865%7CM72587934%7CM72588103
2020-09-25 00:59:57.680 13934-13979/fr.free.nrw.commons D/CookieManager: Domain:commons.wikimedia.org
2020-09-25 00:59:58.297 13934-13979/fr.free.nrw.commons D/OkHttp: <-- 200 https://commons.wikimedia.org/w/api.php?format=json&action=wbgetentities&props=labels&languagefallback=1&ids=M72352190%7CM72352313%7CM72435047%7CM72458952%7CM72459084%7CM72462685%7CM72587723%7CM72587865%7CM72587934%7CM72588103 (618ms, unknown-length body)
2020-09-25 00:59:58.358 13934-13989/fr.free.nrw.commons D/OkHttp: --> GET https://commons.wikimedia.org/w/api.php?action=query&format=json&formatversion=2&generator=allimages&gaisort=timestamp&gaidir=older&prop=imageinfo&iiprop=url|extmetadata&iiurlwidth=640&iiextmetadatafilter=DateTime|Categories|GPSLatitude|GPSLongitude|ImageDescription|DateTimeOriginal|Artist|LicenseShortName|LicenseUrl&gaiuser=Misaochan2&gailimit=10&gaicontinue=20180903090714|Brisbane_Central_6.jpg&continue=gaicontinue||
2020-09-25 00:59:58.360 13934-13989/fr.free.nrw.commons D/CookieManager: Domain:commons.wikimedia.org
2020-09-25 00:59:58.860 13934-13977/fr.free.nrw.commons D/UploadService: Before execution!
2020-09-25 00:59:58.890 13934-13976/fr.free.nrw.commons D/UploadClient: Chunk info
2020-09-25 00:59:58.901 13934-13976/fr.free.nrw.commons D/OkHttp: --> GET https://commons.wikimedia.org/w/api.php?format=json&formatversion=2&errorformat=plaintext&action=query&meta=tokens&type=csrf
2020-09-25 00:59:58.904 13934-13976/fr.free.nrw.commons D/CookieManager: Domain:commons.wikimedia.org
2020-09-25 00:59:59.109 13934-13989/fr.free.nrw.commons D/OkHttp: <-- 200 https://commons.wikimedia.org/w/api.php?action=query&format=json&formatversion=2&generator=allimages&gaisort=timestamp&gaidir=older&prop=imageinfo&iiprop=url|extmetadata&iiurlwidth=640&iiextmetadatafilter=DateTime|Categories|GPSLatitude|GPSLongitude|ImageDescription|DateTimeOriginal|Artist|LicenseShortName|LicenseUrl&gaiuser=Misaochan2&gailimit=10&gaicontinue=20180903090714|Brisbane_Central_6.jpg&continue=gaicontinue|| (751ms, unknown-length body)
2020-09-25 00:59:59.113 13934-13989/fr.free.nrw.commons D/OkHttp: --> GET https://commons.wikimedia.org/w/api.php?format=json&action=wbgetentities&props=labels&languagefallback=1&ids=M71770829%7CM71796197%7CM71796212%7CM71825989%7CM71826028%7CM71838798%7CM72162206%7CM72162245%7CM72162280%7CM72306661
2020-09-25 00:59:59.121 13934-13989/fr.free.nrw.commons D/CookieManager: Domain:commons.wikimedia.org
2020-09-25 00:59:59.347 13934-13982/fr.free.nrw.commons D/EGL_emulation: eglMakeCurrent: 0xebd05c60: ver 2 0 (tinfo 0xebd03be0)
2020-09-25 00:59:59.369 13934-13984/fr.free.nrw.commons D/OkHttp: --> GET https://commons.wikimedia.org/w/api.php?action=query&format=json&formatversion=2&generator=allimages&gaisort=timestamp&gaidir=older&prop=imageinfo&iiprop=url|extmetadata&iiurlwidth=640&iiextmetadatafilter=DateTime|Categories|GPSLatitude|GPSLongitude|ImageDescription|DateTimeOriginal|Artist|LicenseShortName|LicenseUrl&gaiuser=Misaochan2&gailimit=10&gaicontinue=20180819165334|Royal_arcade_Melbourne_3.jpg&continue=gaicontinue||
2020-09-25 00:59:59.394 13934-13984/fr.free.nrw.commons D/CookieManager: Domain:commons.wikimedia.org
2020-09-25 00:59:59.416 13934-13976/fr.free.nrw.commons D/OkHttp: <-- 200 https://commons.wikimedia.org/w/api.php?format=json&formatversion=2&errorformat=plaintext&action=query&meta=tokens&type=csrf (514ms, unknown-length body)
2020-09-25 00:59:59.466 13934-13976/fr.free.nrw.commons D/OkHttp: --> POST https://commons.wikimedia.org/w/api.php?format=json&formatversion=2&errorformat=plaintext&action=upload&stash=1&ignorewarnings=1 (263234-byte body)
2020-09-25 00:59:59.473 13934-13976/fr.free.nrw.commons D/CookieManager: Domain:commons.wikimedia.org
2020-09-25 00:59:59.498 13934-13982/fr.free.nrw.commons D/EGL_emulation: eglMakeCurrent: 0xebd05c60: ver 2 0 (tinfo 0xebd03be0)
2020-09-25 00:59:59.874 13934-13989/fr.free.nrw.commons D/OkHttp: <-- 200 https://commons.wikimedia.org/w/api.php?format=json&action=wbgetentities&props=labels&languagefallback=1&ids=M71770829%7CM71796197%7CM71796212%7CM71825989%7CM71826028%7CM71838798%7CM72162206%7CM72162245%7CM72162280%7CM72306661 (758ms, unknown-length body)
2020-09-25 00:59:59.999 13934-13977/fr.free.nrw.commons D/OkHttp: --> GET https://commons.wikimedia.org/w/api.php?action=query&format=json&formatversion=2&generator=allimages&gaisort=timestamp&gaidir=older&prop=imageinfo&iiprop=url|extmetadata&iiurlwidth=640&iiextmetadatafilter=DateTime|Categories|GPSLatitude|GPSLongitude|ImageDescription|DateTimeOriginal|Artist|LicenseShortName|LicenseUrl&gaiuser=Misaochan2&gailimit=10&gaicontinue=20180819165334|Royal_arcade_Melbourne_3.jpg&continue=gaicontinue||
2020-09-25 01:00:00.016 13934-13977/fr.free.nrw.commons D/CookieManager: Domain:commons.wikimedia.org
2020-09-25 01:00:00.050 13934-13945/fr.free.nrw.commons I/ree.nrw.common: Background concurrent copying GC [...]

2020-09-24 17:35 UTC, maskaravivek commented on app/src/main/java/fr/free/nrw/commons/media/CustomOkHttpNetworkFetcher.java
> +  public OkHttpNetworkFetchState createFetchState(
@misaochan I have added class level Java docs for this file as this class is just a copy of Fresco's network fetcher. I have also added a link to their implementation.

2020-09-24 17:45 UTC, maskaravivek commented
Pasting more logs for ANR for reference. 

```
2020-09-24 10:44:14.584 1536-1643/? E/ActivityManager: ANR in fr.free.nrw.commons.beta
    PID: 4541
    Reason: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{22af855 u0 fr.free.nrw.commons.beta/fr.free.nrw.commons.upload.UploadService}
    Load: 6.78 / 6.29 / 6.0
    CPU usage from 0ms to 6282ms later (2020-09-24 10:44:08.267 to 2020-09-24 10:44:14.549):
      117% 4541/fr.free.nrw.commons.beta: 100% user + 17% kernel / faults: 56145 minor 32 major
      73% 1536/system_server: 46% user + 26% kernel / faults: 18167 minor 62 major
      24% 1915/com.android.systemui: 22% user + 2.5% kernel / faults: 4798 minor 31 major
      13% 594/surfaceflinger: 8.7% user + 4.9% kernel / faults: 495 minor 3 major
      7.9% 559/android.hardware.graphics.composer@2.1-service: 3% user + 4.9% kernel / faults: 209 minor 1 major
      7% 12218/com.luutinhit.lockscreennotificationsios:ios_notification: 5.2% user + 1.7% kernel / faults: 4552 minor
      5.5% 463/logd: 1.4% user + 4.1% kernel / faults: 5 minor
      4.1% 2966/com.luutinhit.ioslauncher:ios_launcher: 3% user + 1.1% kernel / faults: 3983 minor 21 major
      3.9% 2193/com.android.phone: 2.8% user + 1.1% kernel / faults: 1604 minor 71 major
      3.8% 2643/adbd: 2.5% user + 1.2% kernel / faults: 747 minor
      3.5% 4266/com.miui.securitycenter.remote: 1.9% user + 1.5% kernel / faults: 3279 minor 67 major
      2.7% 1897/com.google.android.inputmethod.latin: 2% user + 0.6% kernel / faults: 1303 minor 43 major
      2% 2845/com.xiaomi.xmsf: 1.7% user + 0.3% kernel / faults: 3190 minor 62 major
      1.9% 266/kgsl_worker_thr: 0% user + 1.9% kernel
      1.5% 356/mmc-cmdqd/0: 0% user + 1.5% kernel
      0% 911/media.codec: 0% user + 0% kernel / faults: 1956 minor 17 major
      1.5% 12121/com.luutinhit.controlcenter: 0.7% user + 0.7% kernel / faults: 2177 minor 2 major
      1.4% 565/android.hardware.sensors@1.0-service: 0.9% user + 0.4% kernel / faults: 144 minor 1 major
      1.2% 1742/mdss_fb0: 0% user + 1.2% kernel
      1.2% 2270/kworker/u16:6: 0% user + 1.2% kernel
      1.2% 5084/logcat: 0.4% user + 0.7% kernel
      1.1% 432/ueventd: 0.9% user + 0.1% kernel
      0.9% 464/servicemanager: 0.3% user + 0.6% kernel
      0.9% 12084/kworker/u16:2: 0% user + 0.9% kernel
      0% 28193/kworker/u17:4: 0% user + 0% kernel
      0.7% 794/jbd2/dm-1-8: 0% user + 0.7% kernel
      0.7% 1873/VosTXThread: 0% user + 0.7% kernel
      0.7% 1874/VosRXThread: 0% user + 0.7% kernel
      0.7% 29526/kworker/u16:8: 0% user + 0.7% kernel
      0.6% 846/media.extractor: 0.1% user + 0.4% kernel / faults: 1315 minor 7 major
      0% 927/tombstoned: 0% user + 0% kernel / faults: 115 minor 4 major
      0.6% 3239/com.android.settings:remote: 0.4% user + 0.1% kernel / faults: 421 minor
      0.6% 22876/kworker/u17:5: 0% user + 0.6% kernel
      0.4% 7/rcu_preempt: 0% user + 0.4% kernel
      0.4% 579/healthd: 0.1% user + 0.3% kernel
      0.3% 563/android.hardware.memtrack@1.0-service: 0% user + 0.3% kernel
      0.3% 870/netd: 0.3% user + 0% kernel
      0.3% 910/wificond: 0% user + 0.3% kernel
      0.3% 1872/VosMCThread: 0% user + 0.3% kernel
      0.3% 1883/com.android.bluetooth: 0% user + 0.3% kernel / faults: 236 minor 10 major
      0.3% 2238/kworker/u17:1: 0% user + 0.3% kernel
      0.3% 2240/kworker/u17:3: 0% user + 0.3% kernel
      0.3% 2741/kworker/u17:8: 0% user + 0.3% kernel
      0.3% 2806/com.miui.daemon: 0.3% user + 0% kernel / faults: 35 minor
      0.1% 1//init: 0.1% user + 0% kernel / faults: 33 minor
      0.1% 8/rcu_sched: 0% user + 0.1% kernel
      0.1% 10/rcuop/0: 0% user + 0.1% kernel
      0.1% 42/ksoftirqd/4: 0% user + 0.1% kernel
      0.1% 45/rcuop/4: 0% user + 0.1% kernel
      0.1% 53/rcuop/5: 0% user + 0.1% kernel
      0.1% 61/rcuop/6: 0% user + 0.1% kernel
      0.1% 62/rcuos/6: 0% user + 0.1% kernel
      0.1% 69/rcuop/7: 0% user + 0.1% kernel
      0% 70/rcuos/7: 0% user + 0% kernel
      0.1% 216/hwrng: 0% user + 0.1% kernel
      0.1% 345/cfinteractive: 0% user + 0.1% kernel
      0.1% 417/kworker/4:1H: 0% user + 0.1% kernel
      0.1% 465/hwservicemanager: 0% user + 0.1% kernel / faults: 57 minor 2 major
      0% 471/kauditd: 0% user + 0% kernel
      0.1% 549/android.hardware.audio@2.0-service: 0% user + 0.1% kernel / faults: 88 minor 1 major
      0.1% 560/android.hardware.health
```

2020-09-24 19:31 UTC, maskaravivek commented
@misaochan I have fixed the UI issues and the ANR. Everything should work fine now.

2020-09-25 12:57 UTC, misaochan commented
Have not tested the changes but will merge so @neslihanturan can base her PR on top of it. Will test again and get back to you later. :)

2020-09-25 12:57 UTC, merged