fixes Progress Bar Visibility change with Orientation Change and login process terminated (#4001)
commons-app/apps-android-commons pull request #4028
Opened 2020-11-11 10:04 UTC by Prince-kushwaha

**Description (required)**
Fixes #4001 
What changes did you make and why?
**Bug** is due to the restart of LoginActivity on the configuration change 
* Overrides the onSaveInstanceState method and onRestoreInstanceState method in LoginActivity.java
* In onSaveInstanceState save  ProgressDailog state or visiblity and text of TextView(errorMessage)
* In onRestoreInstanceState restore All saved Data

**Tests performed (required)**
Tested prodDebug on Redmi Y3 level 29

**Screenshots (for UI changes only)**

![20201111_145410](https://user-images.githubusercontent.com/65972015/98796606-9531d300-2431-11eb-8a24-bb86c5f274df.gif)

2020-11-17 12:11 UTC, Prince-kushwaha commented
Anyone review my pull request #4028

2020-11-17 16:03 UTC, misaochan requested changes
Formatting needs a bit of work

2020-11-17 16:03 UTC, misaochan commented on app/src/main/java/fr/free/nrw/commons/auth/LoginActivity.java
> +
Could you look into the formatting please? There are random whitespaces where they should not exist.

2020-11-17 16:03 UTC, misaochan commented on app/src/main/java/fr/free/nrw/commons/auth/LoginActivity.java
> +        }else{
Please refer to codestyle, there should be whitespaces here and in other `else` statements.

2020-11-17 16:37 UTC, Prince-kushwaha commented
Ok i change the codestyle according to docs

2020-11-20 13:10 UTC, ashishkumar468 reviewed
Looks good to me @Prince-kushwaha, I see a few irrelevant white spaces please fix them

2020-11-20 13:13 UTC, Prince-kushwaha commented
ok I fixes this

2020-11-23 17:41 UTC, merged