fixes #4081
commons-app/apps-android-commons pull request #4085
Opened 2020-12-07 15:48 UTC by Prince-kushwaha

**Description (required)**
Fixes #4081 
What changes did you make and why?
fixes NullPointerexception in ContributionsFragment and FavoritiesFragment when backButton is pressed

**Tests performed (required)**
Android Device :Redmi Y3
API :29

2020-12-08 01:44 UTC, domdomegg commented on app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java
> +    static MediaDetailPagerFragment mediaDetailPagerFragment;
I don't think this should be static - there should be a `MediaDetailPagerFragment` per `ContributionsFragment`

2020-12-08 01:45 UTC, domdomegg commented on app/src/main/java/fr/free/nrw/commons/bookmarks/BookmarkListRootFragment.java
> +        ((MainActivity) getActivity()).setSelectedItemId(NavTab.CONTRIBUTIONS.code());
Could avoid code duplication (lines 184 and 188) by combining if statements

2020-12-08 01:46 UTC, domdomegg commented on app/src/main/java/fr/free/nrw/commons/bookmarks/BookmarkListRootFragment.java
> +    //check medaiDetailPage fragment is not null then we check medaiDetail.is Visible or not to avoid NullPointerException
nit: typos

2020-12-08 01:46 UTC, domdomegg commented on app/src/main/java/fr/free/nrw/commons/bookmarks/BookmarkListRootFragment.java
> +        ((MainActivity) getActivity()).showTabs();
All code paths end with `((MainActivity) getActivity()).showTabs();` - we could move that to the end to reduce code duplication

2020-12-22 12:58 UTC, neslihanturan requested changes
Hey @Prince-kushwaha , some of the reviews are not done yet. Can you make sure you have fixed all reviews? I agree @domdomegg with his reviews.

2020-12-22 13:18 UTC, Prince-kushwaha commented
Ok

2020-12-23 10:56 UTC, Prince-kushwaha commented
@neslihanturan  see the second pull request of this pull request #4104 becouse this branch is delected

2020-12-23 10:56 UTC, closed without merging

2020-12-23 11:03 UTC, Prince-kushwaha commented
@neslihanturan see the another pull request of this pull request #4104 becouse this branch is delect by mistake