fix app Crash when tapping on the nearbyNotification
commons-app/apps-android-commons pull request #4139
Opened 2020-12-28 09:24 UTC by Prince-kushwaha

**Description (required)**
Fixes #4086 

What changes did you make and why?
->Implement CallBack interface in MainActivity ->centerMapToPlace() function 

**Tests performed (required)**
Android Device:Redmi y3;
API :28

2020-12-31 12:02 UTC, Prince-kushwaha commented
@nicolas-raoul view my PR

2021-01-01 13:56 UTC, neslihanturan requested changes
Hey @Prince-kushwaha , thanks for your changes. This time the code looks much better and it solves the issue. Just some minor style issues are left. Please see my reviews.

2021-01-01 13:56 UTC, neslihanturan commented on app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java
> +    public void setNearbyParentFragmentListener(final NearbyParentFragmentListener nearbyParentFragmentListener) {
why this needed to be final?

2021-01-01 13:56 UTC, neslihanturan commented on app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java
> +    public interface  NearbyParentFragmentListener{
This interface name can be more definitive ie. NearbyParentFragmentInstanceReadyCallback

2021-01-01 13:56 UTC, neslihanturan commented on app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java
> +        void onMapReady();
Lets rename this method to onReady() , since this has nothing to do with map

2021-01-01 16:33 UTC, neslihanturan approved these changes
Thanks for fast responses! Congratz:)

2021-01-01 16:33 UTC, merged