fixes some bugs in Peer Review activity upon switching orientation
commons-app/apps-android-commons pull request #4176
Opened 2021-01-15 08:03 UTC by Prince-kushwaha

**Description (required)**

Fixes #4143 

What changes did you make and why?
In reviewActivity overrides the two function onResume() and onPause() 

**Tests performed (required)**
Android:Redmi y3;

2021-01-17 12:26 UTC, Prince-kushwaha commented
@nicolas-raoul  review my PR

2021-01-19 17:40 UTC, Prince-kushwaha commented
@misaochan @madhurgupta10 review my PR

2021-01-25 13:45 UTC, neslihanturan commented
Hey @Prince-kushwaha , please add screen cast to display this changes solve the issue.

2021-01-25 15:28 UTC, Prince-kushwaha commented
@neslihanturan i add screen shot

2021-02-19 14:08 UTC, Prince-kushwaha commented
@nicolas-raoul @neslihanturan please review my this PR

2021-02-20 01:25 UTC, nicolas-raoul requested changes
I confirm that the crash:
- still happens in master
- is fixed by this PR

2021-02-20 01:25 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/review/ReviewActivity.java
> +    private ReviewImageFragment reviewImageFragment;
Please add javadoc

2021-02-20 01:25 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/review/ReviewActivity.java
> +        reviewPager.setOffscreenPageLimit(2);
Please add a comment explaining why the number `2`.

2021-02-20 01:25 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/review/ReviewActivity.java
> +            reviewImageFragment=getInstanceOfReviewImageFragment();
Please a space before and after `=`.
Here and in other similar lines of your PR.

2021-02-20 01:25 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/review/ReviewActivity.java
> +            reviewImageFragment=getInstanceOfReviewImageFragment();
Please a space before and after `=`.
(here and in other similar lines of your PR)

2021-02-20 01:25 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/review/ReviewActivity.java
> +        int pos=reviewPager.getCurrentItem();
In Java we prefer to use full words for variable names, unlike other languages like C.

2021-02-20 01:25 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/review/ReviewActivity.java
> +        reviewImageFragment= (ReviewImageFragment) reviewPagerAdapter.instantiateItem(reviewPager,pos);
Please add a space after each `,`

2021-02-20 10:11 UTC, nicolas-raoul requested changes

2021-02-20 10:11 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/review/ReviewActivity.java
> +        reviewImageFragment = (ReviewImageFragment) reviewPagerAdapter.instantiateItem(reviewPager,currentItemOfReviewPager);
space after `,`

2021-02-20 12:14 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/review/ReviewActivity.java
> +    private ReviewImageFragment reviewImageFragment;
Any difficulty to address this? Feel free to take your time though :-)

2021-02-20 14:29 UTC, nicolas-raoul requested changes

2021-02-20 14:29 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/review/ReviewActivity.java
> +    public ReviewImageFragment getInstanceOfReviewImageFragment(){
Sorry, javadoc needed here too

2021-02-21 01:57 UTC, nicolas-raoul approved these changes

2021-02-21 01:58 UTC, merged