fix-Incomplete Nearby List shown in Landscape mode (#2270)
commons-app/apps-android-commons pull request #4188
Opened 2021-01-18 06:16 UTC by Prince-kushwaha

**Description (required)**

Fixes #2270

What changes did you make and why?
Cause of Bug
 when the view is generated in portrait  mode  the height was set according to the portrait mode, when we rotate screen to Landscope mode   the height of the container remained same as of portrait, due to which we were not able to see the rest of the list which was already generated but was hidden 

To solve this issue there need to update the height of  **rlBottomSheet.getLayoutParams().height** on configuration or orientation change of device screen 

**Tests performed (required)**
Android Device:Redmi y3 

**Screenshots (for UI changes only)**

![WhatsApp Image 2021-01-18 at 11 38 27 AM](https://user-images.githubusercontent.com/65972015/104878508-18b3f700-5982-11eb-84c8-dd3a1b89f1e4.jpeg)

![WhatsApp Image 2021-01-18 at 11 38 28 AM](https://user-images.githubusercontent.com/65972015/104878610-49942c00-5982-11eb-9721-b4d1fc27edac.jpeg)

2021-01-20 06:02 UTC, Prince-kushwaha commented
@madhurgupta10 Review my this PR

2021-02-08 14:06 UTC, neslihanturan approved these changes
Thanks @Prince-kushwaha , this works as intended. Thanks a lot for reading and investigating the old related, closed PR.

2021-02-08 14:15 UTC, neslihanturan requested changes
I just recognized setLayoutParams(params) is not called. By only getting and assigning layout params we can not make sure new layout params will work. It can vary depending to Android version, so it won't always work if we don't call it. We should always use setLayoutParams method. Please add it and I will merge. For more explanation see: https://stackoverflow.com/questions/35500090/why-do-we-use-setlayoutparams

2021-02-15 15:19 UTC, neslihanturan requested changes

2021-02-15 15:19 UTC, neslihanturan commented on app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java
> +        ViewGroup.LayoutParams rlBottomSheetLayoutParams=rlBottomSheet.getLayoutParams();
could you please add single spaces before and after "=" to keep style guides?

2021-02-15 18:00 UTC, neslihanturan approved these changes
Thanks @Prince-kushwaha :)

2021-02-15 18:01 UTC, merged