Added bookmark section in not-logged-in version
commons-app/apps-android-commons pull request #4256
Opened 2021-02-20 15:25 UTC by 4D17Y4

**Description (required)**

Fixes #4250 

What changes did you make and why?

BookmarkPagerFragment 
* Added a constructor parameter which tells Adapter if onlyPicture fragment of bookmark is to initialized (i.e. when user not logged in).
* If onlyPicture is true we do not add location bookmark fragment in the pages.

BookmarkFragment
* Used preferences to check if the user is logged in.
* Added a method to set up the Tab Layout that considers the case when the adapter has only one element.

NavTabLoggedOut
* Added 'favorites' navTabElement.

BookmarksPagerAdaterTests.kt
* Updated the function according to the new constructor.

MainActivity
* Minor inhancement as it showed uploaded from mobile instead of explore.
 

**Tests performed (required)**

Tested betaDebug on Nokia 6.1+ with API level 29.

2021-02-20 15:26 UTC, 4D17Y4 commented
Up for review and suggestions.
@neslihanturan, @nicolas-raoul.

2021-02-21 01:18 UTC, nicolas-raoul requested changes
Minor style change.
Also, would it make sense to make a new unit test?

2021-02-21 01:18 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/bookmarks/BookmarkFragment.java
> +    if(adapter.getCount()==1){
We usually put spaces before and after `==` and other logical operators, see for instance the code snippets found at http://www.literateprogramming.com/javaconv.pdf

2021-02-21 12:22 UTC, 4D17Y4 commented
Yus @nicolas-raoul ,
I think I can add that.

2021-02-21 13:26 UTC, 4D17Y4 commented
Added new unit test.

2021-02-21 15:23 UTC, nicolas-raoul approved these changes
Works well, thanks!

2021-02-21 15:23 UTC, merged