fix:Explore Search: No title bar for item, non-existent menu for item, wrongly-worded menu for category
commons-app/apps-android-commons pull request #4274
Opened 2021-02-24 05:00 UTC by Prince-kushwaha

**Description (required)**

Fixes #4271 

What changes did you make and why?

* add toolbar in WikidataItemDetailsActivity
* minor change 
 * add javadoc

**Tests performed (required)**

Tested { ProdDebug} on {name of device :Redmi 4} with API level {25,28}.

**Screenshots (for UI changes only)**
![Screenshot_2021-02-24-10-13-45-864_fr free nrw commons](https://user-images.githubusercontent.com/65972015/108949832-264c5300-768b-11eb-9914-0666ac3ba742.jpg)

![Screenshot_2021-02-24-10-14-28-861_fr free nrw commons](https://user-images.githubusercontent.com/65972015/108949817-1c2a5480-768b-11eb-96e4-82281e5a1741.jpg)

2021-02-26 09:28 UTC, Prince-kushwaha commented
@nicolas-raoul rewiew my this PR

2021-02-28 02:44 UTC, Prince-kushwaha commented
up for review @nicolas-raoul , @neslihanturan

2021-03-01 14:48 UTC, neslihanturan requested changes

2021-03-01 14:48 UTC, neslihanturan commented on app/src/main/res/values/strings.xml
> +  <string name="view_item_page">View item page</string>
What about renaming "view_item_page" to "menu_view_item_page", just to be consistent with the string above ("menu_view_category_page") ?

2021-03-01 14:50 UTC, neslihanturan commented
Hey @Prince-kushwaha , thanks for the PR. There are 3 issues in the issue linked (ideally they should have been separated issues). 
1- The text "view file page" should be "View category page". (PR solves this)
2- Item should have a tree dot menu containing "View item page" (PR solves this)
3- Adds toolbar to media item when it is selected from search->item (PR solves this)

So I am good to merge this PR as soon as the minor string naming issue is solved, thanks :)

2021-03-03 08:01 UTC, nicolas-raoul requested changes
Great PR, it works perfectly for all 3 points, as Neslihan mentioned.
I found a few minor details worth fixing.

2021-03-03 08:01 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/explore/depictions/WikidataItemDetailsActivity.java
> +     * this function inflate the menu
this -> This (first letter uppercase in javadoc)
inflate -> inflates

2021-03-03 08:01 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/explore/depictions/WikidataItemDetailsActivity.java
> +     * Currently only 1 choice is available to open Wikidataitem details page in browser
Wikidataitem -> Wikidata item

2021-03-03 12:39 UTC, neslihanturan approved these changes
Thanks for the cooperation @Prince-kushwaha :)

2021-03-03 12:39 UTC, merged