#4048 - "copy to subsequent media" button
commons-app/apps-android-commons pull request #4308
Opened 2021-03-28 18:29 UTC by Pratham2305

**Description (required)**

Fixes #4048

What changes did you make and why?

Replaced the "copy previous captions & description" button, Added methods in UploadMediaPresenter that will copy and fetch the caption & description respectively, and also added a onBecameVisible() method in UploadMediaFragment which will be called after pressing next/previous button, this method will fetch and set the copied media details. And other minor changes in UploadMediaFragment, UploadRepository, and unit tests.

**Tests performed (required)**

Tested betaDebug on Pixel 3 with API level 29.

2021-04-01 14:46 UTC, nicolas-raoul commented
Nice!
I just tried it for two pictures, it seems to work great.
I will perform a few more tests tomorrow, thanks for your patience.

2021-04-01 15:28 UTC, neslihanturan requested changes
Hey, thanks a lot for the PR @Pratham2305 :) I attempted to try it, however there is no button in betaDebug or I cannot find it. Can you make sure you added UI screen shoots for UI changes so that I can find the button if exists.
![resim](https://user-images.githubusercontent.com/3127881/113316802-69978280-9317-11eb-8bd7-d83b74253214.png)

![resim](https://user-images.githubusercontent.com/3127881/113316822-6e5c3680-9317-11eb-9aa7-4d2d91be5cc3.png)

2021-04-02 06:00 UTC, nicolas-raoul requested changes

2021-04-02 06:00 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java
> +    @Override
We have a rule that you must add javadoc for all new methods (even overrides). It can be very simple, just say when this method is called. Thanks!

2021-04-02 06:00 UTC, nicolas-raoul commented
@neslihanturan The button only appears for a grouped upload (which I think makes sense). Would you mind trying to upload 2 or more pictures at the same time? :-)

I tested this PR more today, in various languages and various numbers, caption and description. It works great so I would actually be in favor of merging as soon as the 3 minor details I reviewed are fixed.

2021-04-02 06:11 UTC, neslihanturan commented
I was thinking that this issue is about using title of previous single upload (we had such a button previously and I was using it often:) ). According to @nicolas-raoul 's explanations I have tested the PR again and works like a charm:)

2021-04-02 06:12 UTC, merged