Added LocationUtilsTest for LocationUtils
commons-app/apps-android-commons pull request #4319
Opened 2021-04-03 17:24 UTC by 4D17Y4

**Description (required)**
Added LocationUtilsTest for LocationUtils

**Tests performed (required)**

Tested BetaDebug on Nokia 6.1+ API level 29.

2021-04-06 07:47 UTC, madhurgupta10 requested changes

2021-04-06 07:47 UTC, madhurgupta10 commented on app/src/test/kotlin/fr/free/nrw/commons/utils/LocationUtilsTest.kt
> +import org.hamcrest.MatcherAssert.assertThat
Delete this unused import

2021-04-06 07:47 UTC, madhurgupta10 commented on app/src/test/kotlin/fr/free/nrw/commons/utils/LocationUtilsTest.kt
> +    fun testMapBoxLatLngToCommonsLatLng() {
Add a check for accuracy also!

2021-04-06 07:47 UTC, madhurgupta10 commented on app/src/test/kotlin/fr/free/nrw/commons/utils/LocationUtilsTest.kt
> +    fun testCommonsLatLngToMapBoxLatLng() {
Add a check for altitude also!

2021-04-06 09:14 UTC, 4D17Y4 commented
Done @madhurgupta10 .
Thanks.

2021-04-06 09:17 UTC, madhurgupta10 approved these changes

2021-04-08 12:40 UTC, neslihanturan approved these changes
Thanks @4D17Y4 :)

2021-04-08 12:40 UTC, merged