Fixes Issue #4300 -> Limited connection mode banner occupies too much space
commons-app/apps-android-commons pull request #4339
Opened 2021-04-08 07:17 UTC by VishnuSanal

**Description**

Fixes #4300 

What changes did you make and why?

`fragment_contributions.xml` -> For updating Limited connection mode banner
`dimens.xml` -> For adding `limited_connection_enabled_layout_height` dimension

**Tests performed**

Tested app:assembleProdDebug

**Screenshots**

![IMG_20210406_005057](https://user-images.githubusercontent.com/50027064/113616184-692e1d00-9672-11eb-8eb5-6f23a6ce81b0.jpg)

2021-04-08 08:37 UTC, vinayak0505 commented
Review by student

nice work, but just one thing on my device the as you can see in the after image the "on" is not visible, may be setting layout height to wrap content will solve the issue or in image view you can add adjustviewbond = "true" 

before
![Screenshot_20210408-140322](https://user-images.githubusercontent.com/56196007/113995211-add4d680-9873-11eb-8421-c9710be32787.png)
after
![Screenshot_20210408-135011](https://user-images.githubusercontent.com/56196007/113995160-a01f5100-9873-11eb-9cfa-9b4be2feaea1.png)

2021-04-08 09:00 UTC, VishnuSanal commented
@vinayak0505 Thank you for your suggestions :) I'm really sorry to have missed that. I think (if we're going with this layout) we can change that `LinearLayout` to a simple `TextView` with `DrawableStart`, which would reduce overdraw & fix this bug too! Thanks again for your suggestions :D

2021-04-12 14:42 UTC, neslihanturan requested changes

2021-04-12 14:42 UTC, neslihanturan commented on .idea/codeStyles/Project.xml
> +      <option name="PACKAGES_TO_USE_STAR_IMPORTS">
I know this is a draft but this edits should be reverted since they are not mandatory for the related issue. We change only relevant lines :)

2021-04-12 14:42 UTC, neslihanturan commented on app/src/main/res/layout/fragment_contributions.xml
> +  android:layout_width="match_parent"
I see some irrelevant changes in this file too, please make sure you edited only the lines that should be edited:)

2021-04-24 20:30 UTC, closed without merging