panoramic images fixed
commons-app/apps-android-commons pull request #4368
Opened 2021-04-20 09:17 UTC by 4D17Y4

**Description (required)**

Fixes #1815

What changes did you make and why?

Updated image thumb URL depending on the height received.

**Tests performed (required)**

Tested BetaDebug on Nokia 6.1 with API level 29.

2021-04-20 09:29 UTC, 4D17Y4 commented
Instead of making another API call, I Figured that we can update the URL which will be the same as if returned from the query.
This reduces the API call as otherwise, we have to call the API multiple times just to get the different image URL.

I understand that this could break if there is some update in the URL returned from the API, but as we have used a similar dependent procedure to get the author of the image I preferred this one.

If this is not acceptable I'll make the API calls to fetch the thumbURL and update the URL.

Up for review @nicolas-raoul , @neslihanturan .
Thanks.

2021-04-20 09:59 UTC, nicolas-raoul requested changes
Great idea to make one less API call!

2021-04-20 09:59 UTC, nicolas-raoul commented on data-client/src/main/java/org/wikipedia/gallery/ImageInfo.java
> +                thumbUrl = (new StringBuilder(thumbUrl)).replace(position,position+toReplace.length(),"/"+thumbWidth+"px").toString();
space after `,`, space before and after `+`

2021-04-20 09:59 UTC, nicolas-raoul commented on data-client/src/main/java/org/wikipedia/gallery/ImageInfo.java
> +     * Updates the ThumbUrl if image dimensions are not sufficient.
Readers might not know what `not sufficient` means, so could you please say it more explicitly? Do not hesitate to explain the specific case of panoramic images.

2021-04-20 09:59 UTC, nicolas-raoul commented on data-client/src/main/java/org/wikipedia/gallery/ImageInfo.java
> +
Is this empty line intended?

2021-04-20 09:59 UTC, nicolas-raoul commented on data-client/src/main/java/org/wikipedia/gallery/ImageInfo.java
> +    public int getThumbWidth() { return thumbWidth; }
javadoc (also for the next one)

2021-04-20 09:59 UTC, nicolas-raoul commented on data-client/src/main/java/org/wikipedia/gallery/ImageInfo.java
> +    final private int thresholdHeight = 220;
If it does not change, how about making it `static` maybe?

2021-04-20 11:58 UTC, nicolas-raoul requested changes

2021-04-20 11:58 UTC, nicolas-raoul commented on data-client/src/main/java/org/wikipedia/gallery/ImageInfo.java
> +    final private static int thresholdHeight = 220;
The convention for constants is uppercase: `THRESHOLD_HEIGHT`
This is worth a read: https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html :-)

2021-04-20 12:20 UTC, nicolas-raoul commented
Strangely the super-high resolution file [Dunes of Amrum](https://commons.wikimedia.org/wiki/File:Dunes_of_Amrum.jpg) is pixelated (even when setting `THRESHOLD_HEIGHT` to `500`):
![adb](https://user-images.githubusercontent.com/99590/115394133-6ceaa380-a21d-11eb-8047-4f977df6e816.png)
Any idea why?

2021-04-20 13:35 UTC, 4D17Y4 commented
Is the issue common to all images?
Or only this particular entry?

Also, do you find any change with this commit in this item's thumbnail?

I'll look into it.
Thanks for notifying

2021-04-20 13:51 UTC, nicolas-raoul commented
I notice the low resolution only for this image (not for all images).
It is much worse on master, though.

Would you mind putting breakpoints and checking what thumbnail API calls are made to get the Dunes of Amrum thumbnail?

2021-04-21 19:47 UTC, 4D17Y4 commented
I've uploaded this same image from the app under test ( sandbox ) , with the name test_panorama and I can reproduce this. 
All the URL seem perfectly fine, the parameters are accurate and clicking on links end up to the high-quality image which its meant to be, but somehow the image view or drawee view is not getting the quality image.

As this is the case with the uploaded image too, I suspect that this may be the case with every image that has width to hight ratio about 15 or more.

I'm looking into the image views attribute that may cause an exception.
If any other image shows this behavior, do notify me. It'll help me confirm that this is due to the dimensions.

Thanks.

2021-04-22 05:33 UTC, nicolas-raoul commented
How is the image returned by the API, is it pixelated already?
Or does the pixelation happen afterwards, when displaying it?

2021-04-23 20:45 UTC, 4D17Y4 commented
I've logged the image url to check for it and here is the result.

Just before calling the function `updateThumbUrl()`
> 2021-04-24 01:55:38.107 30128-30205/fr.free.nrw.commons.beta I/Aditya: Before change https://upload.beta.wmflabs.org/wikipedia/commons/thumb/3/36/Test_panorama.jpg/640px-Test_panorama.jpg


Just after calling the function `updateThumbUrl()`
> 2021-04-24 01:55:38.108 30128-30205/fr.free.nrw.commons.beta I/Aditya: After change https://upload.beta.wmflabs.org/wikipedia/commons/thumb/3/36/Test_panorama.jpg/15238px-Test_panorama.jpg


Before setting it to the imageView in contributions.
> 2021-04-24 01:55:45.070 30128-30128/fr.free.nrw.commons.beta I/Aditya: ImageSource https://upload.beta.wmflabs.org/wikipedia/commons/thumb/3/36/Test_panorama.jpg/15238px-Test_panorama.jpg

U can see the links are perfectly fine with respect to the quality of images.

**Note : I used the threshold as 1000 in this test.**


It might be fresco doing the quality degrade behind the scene.
I'll test it with other methods for loading the image to the view and inform of any update.

Thanks.

2021-04-24 07:43 UTC, nicolas-raoul commented
Interesting!
Please do not hesitate to create a new Fresco bug (https://github.com/facebook/fresco/issues I guess?) if there is none about it already. The best is to create a minimal GitHub project that uses just Fresco, and performs only this operation, showing the bug in the smallest project possible.

2021-05-14 12:17 UTC, madhurgupta10 commented
@4D17Y4 did you try to update Fresco to the latest version?

2021-05-15 09:52 UTC, 4D17Y4 commented
I did update to the latest version but it didn't help.
I'll check it again 
Thanks.

2021-06-21 04:47 UTC, madhurgupta10 commented
Fixed in #4467

2021-06-21 04:47 UTC, closed without merging