Show media details fragment when on clicking image of  Peer Review
commons-app/apps-android-commons pull request #4374
Opened 2021-04-24 17:15 UTC by Prince-kushwaha

**Description (required)**

Fixes #2763 

What changes did you make and why?

 * Currently on clicking the image of peer review it does nothing. Now it will show the media detail fragment on clicking the image of peer review 
* Add javadoc
* Reformated code of  ReviewActivity.xml

**Tests performed (required)**

Tested {Prodebug,} on {Redmi note 4,redmi y3} with API level {29,25}

2021-04-27 03:18 UTC, Prince-kushwaha commented
@nicolas-raoul please review this one

2021-04-27 10:00 UTC, nicolas-raoul requested changes

2021-04-27 10:00 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java
> +        // detail proovider is null when fragment is show in review activity
proovider -> provider
show -> shown

2021-04-27 14:39 UTC, madhurgupta10 commented
@Prince-kushwaha can you add unit tests for the all-new methods?

2021-04-27 14:42 UTC, nicolas-raoul commented
It works great :-)

2021-04-27 14:42 UTC, Prince-kushwaha commented
@madhurgupta10 yes i add unit test for methods

2021-04-28 11:29 UTC, Prince-kushwaha commented
@madhurgupta10  help me how I run Unit Test-ReviewActivityTest It does not have option to run the test

2021-04-28 12:35 UTC, madhurgupta10 commented
You can run tests from Android Studio like this

[image: Capture.PNG]

On Wed, 28 Apr 2021 at 16:59, Prince kushwaha ***@***.***>
wrote:

> @madhurgupta10 <https://github.com/madhurgupta10> help me how I run Unit
> Test-ReviewActivityTest It does not have option to run the test
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/commons-app/apps-android-commons/pull/4374#issuecomment-828378913>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHL77I3GHQZDKR6MUTNDMCLTK7WS3ANCNFSM43QKVAAA>
> .
>

2021-04-29 06:25 UTC, madhurgupta10 requested changes

2021-04-29 06:25 UTC, madhurgupta10 commented on app/src/main/java/fr/free/nrw/commons/review/ReviewActivity.java
> +    public void setUpMediaDetailFragment() {
No need to make them public for unit tests

2021-04-29 06:25 UTC, madhurgupta10 commented on app/src/main/java/fr/free/nrw/commons/review/ReviewActivity.java
> +    public void setUpMediaDetailOnOrientation() {
No need to make them public for unit tests

2021-04-29 06:25 UTC, madhurgupta10 commented on app/src/test/kotlin/fr/free/nrw/commons/review/ReviewActivityTest.kt
> +        activity.setUpMediaDetailFragment()
For private methods test like this

```
val method: Method = ClassToTest::class.java.getDeclaredMethod(
            "methodToTest"
        )
        method.isAccessible = true
        method.invoke(classTestObject)
```

2021-04-29 06:27 UTC, madhurgupta10 commented
@Prince-kushwaha can you also post the screenshot of the code coverage for this file?

2021-04-29 12:41 UTC, Prince-kushwaha commented
@madhurgupta10 code coverage for this file
 
![tes](https://user-images.githubusercontent.com/65972015/116552032-321bf600-a916-11eb-893e-7fc493cc6b62.PNG)

2021-05-03 00:39 UTC, nicolas-raoul approved these changes
Looks OK from my point of view.
@madhurgupta10 anything to add? :-)

2021-05-03 17:59 UTC, madhurgupta10 commented
@Prince-kushwaha I tested your PR, your tests are not covering most of the new lines added, if you can cover maximum lines then it would be great (Can be done in a separate PR)

@nicolas-raoul I think we can merge this one!

![Capture](https://user-images.githubusercontent.com/30932899/116913586-4e49cb00-ac67-11eb-9691-6bf5955fbbff.PNG)

2021-05-03 18:00 UTC, madhurgupta10 approved these changes

2021-05-10 16:07 UTC, neslihanturan approved these changes
Works as intended, nice job @Prince-kushwaha , thanks!

2021-05-10 16:07 UTC, merged