Added an option to Remove a new language description while uploading
commons-app/apps-android-commons pull request #4406
Opened 2021-05-10 12:14 UTC by Ayan-10

**Description**

Fixes #2810 

What changes did you make and why?

Sometimes, a user might accidentally click the "+" button for adding a new language while uploading an image, there was no option to remove it in the current app. So I added a remove button so that the user can remove it.

**Tests performed**

Tested 3.0.0-lastest master on Pixel 4 with API level 27.

**Screenshots**

<img src=https://user-images.githubusercontent.com/71203077/117655615-ed654a00-b1b4-11eb-936f-1140a369573f.png width=300/>

2021-05-14 10:44 UTC, nicolas-raoul requested changes
It works great!
Just a javadoc request.
It reduces vertical space to view the picture when writing metadata, but I guess that's unavoidable.

2021-05-14 10:44 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/upload/UploadMediaDetailAdapter.java
> +    public void removeDescription(final UploadMediaDetail uploadMediaDetail, final int position) {
javadoc

2021-05-14 14:07 UTC, Ayan-10 commented
@nicolas-raoul I added java docs. Hope it's up to the mark now.

2021-05-15 00:14 UTC, nicolas-raoul approved these changes

2021-05-15 00:14 UTC, merged