Added option for sharing achievements and a back button in ProfileActivity
commons-app/apps-android-commons pull request #4489
Opened 2021-07-02 19:53 UTC by Ayan-10

**Description**

Added option for sharing achievements and a back button in ProfileActivity. Also added username at the top of the toolbar

Fixes #4312 

What changes did you make and why?

There is no option in the current app for sharing achievements and it also doesn't have a back button in Profile Activity. So I added those things.

**Tests performed (required)**

Tested latest master on Pixel with API level 30.

2021-07-04 16:54 UTC, madhurgupta10 commented
@Ayan-10 Could you please add tests for all the new lines you added to ProfileActivity?

2021-07-04 18:05 UTC, Ayan-10 commented
@madhurgupta10 I am not good at writing tests and I recently started learning testing. But I will definitely give it a try.

2021-07-04 18:08 UTC, Ayan-10 commented
Also, @madhurgupta10 If you can suggest me some good resources for learning testing. Please tell me. 

Thanks.

2021-07-05 05:25 UTC, madhurgupta10 commented
@Ayan-10 You can look at the unit tests that are written for other methods, the best way to learn is by doing :)

2021-07-05 13:12 UTC, Ayan-10 commented
@madhurgupta10 Thank you so much for your advice. I have written the tests. Maybe there are some mistakes. Please let me know about it. I am open to learn.

2021-07-05 14:55 UTC, madhurgupta10 commented
@Ayan-10 Can you post a screenshot of the code coverage report for ProfileActivity and AchievementsFragment where we can see total lines hits/miss?

Feel free to ask any questions you have :)

2021-07-05 19:39 UTC, Ayan-10 commented
Yes, I can. But I faced some problems while running tests, first time `Command line is too long. Shorten command line for ReviewActivityTest or also for Android JUnit default configuration`  this error occurred then I fixed it by choosing to shorten command line : **JAR manifest**. But then whenever I am running any test case in the project, it's running forever and consuming lots of data. Can you help me with that? 

<img width="960" alt="2021-07-06" src="https://user-images.githubusercontent.com/71203077/124510032-a3819480-ddf0-11eb-9964-3363010d7909.png">

2021-07-06 06:53 UTC, madhurgupta10 commented
Try changing your JRE from default to 1.8
![Screenshot 2021-07-06 122132](https://user-images.githubusercontent.com/30932899/124555554-d8bfce00-de54-11eb-87be-bc9125187b07.png)
![Screenshot 2021-07-06 122106](https://user-images.githubusercontent.com/30932899/124555562-da899180-de54-11eb-8ead-362e51672597.png)

2021-07-06 06:56 UTC, madhurgupta10 commented
Also set your Shorten command line to classpath file

![Screenshot 2021-07-06 122448](https://user-images.githubusercontent.com/30932899/124555950-4e2b9e80-de55-11eb-88d5-bdbe7de94b8d.png)

2021-07-06 07:36 UTC, Ayan-10 commented
@madhurgupta10 I tried your suggestion setting JRE to 1.8 and shorten command line to classpath. But still, it's doing the same.

2021-07-06 07:45 UTC, madhurgupta10 commented
@Ayan-10 Unit tests can run without a virtual or a physical device, try running a single test and see if works or not. Also, post a screenshot of your test configuration.

2021-07-06 08:02 UTC, Ayan-10 commented
@madhurgupta10 This kind of client tests are running as expected.

<img width="960" alt="2021-07-06 (1)" src="https://user-images.githubusercontent.com/71203077/124563296-89ca6680-de5d-11eb-96ee-4ab271181336.png">

But when It comes to test of any activity or fragment files. It's running infinitely and consuming lots of data. 

<img width="960" alt="2021-07-06 (3)" src="https://user-images.githubusercontent.com/71203077/124564319-913e3f80-de5e-11eb-9c57-a0f27a92c490.png">


This is the configuration.

<img width="960" alt="2021-07-06 (2)" src="https://user-images.githubusercontent.com/71203077/124564011-3b699780-de5e-11eb-96fb-8dcb46595d7f.png">

2021-07-06 08:15 UTC, madhurgupta10 commented
@Ayan-10 Your configurations look good to me, what version of Gradle Plugin are you using?

2021-07-06 08:23 UTC, Ayan-10 commented
`        classpath 'com.android.tools.build:gradle:4.0.1'`

`distributionUrl=https\://services.gradle.org/distributions/gradle-6.2.2-all.zip`

I didn't change anything in Gradle. It's the same as master.

2021-07-06 08:47 UTC, madhurgupta10 commented
@Ayan-10 Plugin version seems good to me, not sure what is causing the issue.

Not sure if these would help but few things you can try
1. Try with Looper Mode Paused
2. Increase more RAM allocation for Android Studio, close any other applications, browser running
3. Invalidate Caches and Retry
4. Delete .gradle folder, Clean and Rebuild the project

2021-07-06 11:21 UTC, Ayan-10 commented
@madhurgupta10 Tried everything but nothing worked. I am telling you the way I am running the tests. Maybe there will be some problem. 

1. Going to ProfileActivityTest file
2. Clicking the run button besides `class ProfileActivityTest {`
3. Then clicking Run ProfileActivityTest

Is it ok?

2021-07-07 05:50 UTC, Ayan-10 commented
@madhurgupta10 I did some experiments with tests and find out that only the files which are running with `RobolectricTestRunner`, are causing that problem. The tests without `@RunWith(RobolectricTestRunner::class)` this line, running as expected.

Can you help me with this fact?

2021-07-07 14:09 UTC, Ayan-10 commented
@madhurgupta10 I fixed the issue. Thanks :)

Here is the screenshot of code coverage. Please let me know about any mistakes.

<img width="960" alt="2021-07-07" src="https://user-images.githubusercontent.com/71203077/124773717-d34cab80-df5a-11eb-990b-789986d5154b.png">

2021-07-08 08:46 UTC, madhurgupta10 commented
> @madhurgupta10 I fixed the issue. Thanks :)
> 
> Here is the screenshot of code coverage. Please let me know about any mistakes.
> 
> <img alt="2021-07-07" width="960" src="https://user-images.githubusercontent.com/71203077/124773717-d34cab80-df5a-11eb-990b-789986d5154b.png">

Very good @Ayan-10 what was the solution btw?

For code coverage, can you post a screenshot of the ProfileActivity and AchievementsFragment instead of the package where we can see lines hits (highlighted in green) and miss (highlighted in red)

Lines hit means these lines are being covered in unit tests where miss means the opposite. When we write tests we make sure we cover max lines.

2021-07-08 18:45 UTC, Ayan-10 commented
@madhurgupta10  Actually it's an issue of robolectric. When I found the problem is with robolectric, I started learning it and while doing so I find out robolectric download some jars before running the tests. I also went to Github repo of robolectric and I found an issue regarding this problem. Downloading jars are taking a lot of time. The issue is open now they are working on it to reduce the time. And There is also an issue with android studio. When I run tests it's showing "tests are running" but that's totally misleading. At that time the jars are downloading.

2021-07-08 18:55 UTC, Ayan-10 commented
@madhurgupta10 I posted all the screenshots of ProfileActivity Tests. And I didn't add anything in achievementsFragment, I just removed some variables and methods. That's why I didn't post achievementsFragment Tests. Should I post the screenshots?


<img width="960" alt="2021-07-08 (8)" src="https://user-images.githubusercontent.com/71203077/124974952-0f5f3980-e04b-11eb-88a3-7b23a75231d0.png">
<img width="771" alt="2021-07-08 (9)" src="https://user-images.githubusercontent.com/71203077/124975008-26059080-e04b-11eb-93b6-067b1b97d8a4.png">
<img width="790" alt="2021-07-08 (10)" src="https://user-images.githubusercontent.com/71203077/124975041-2ef66200-e04b-11eb-8694-fcb6fc19c8ec.png">
<img width="722" alt="2021-07-08 (11)" src="https://user-images.githubusercontent.com/71203077/124975082-39b0f700-e04b-11eb-9530-fc94b8989d71.png">
<img width="833" alt="2021-07-08 (7)" src="https://user-images.githubusercontent.com/71203077/124975103-45042280-e04b-11eb-9460-eab0fc04736b.png">

2021-07-09 10:58 UTC, madhurgupta10 commented
@Ayan-10 thanks for posting the screenshots. 91.7% is good coverage but we can still make it to 100% easily.

For the method `onOptionsItemSelected` only the default case is covered, can you add a test for the case where the `if` statement is true?

2021-07-09 18:55 UTC, Ayan-10 commented
@madhurgupta10 I added the cases for if statement true. But I am getting a `NullPointerException` on line 143 on the attached screenshot. The method on `getWindow().getDecorView().findViewById(android.R.id.content);` is giving null as a rootView. Can you help me with that?

<img width="484" alt="2021-07-10" src="https://user-images.githubusercontent.com/71203077/125123529-667d1100-e114-11eb-8add-e98b9bc8ee49.png">

```
    @Test
    @Throws(Exception::class)
    fun testOnOptionsItemSelected() {
        val menuItem: MenuItem = RoboMenuItem(R.menu.menu_about)
        Shadows.shadowOf(Looper.getMainLooper()).idle()
        activity.onOptionsItemSelected(menuItem)
        val menuItemShare: MenuItem = RoboMenuItem(R.id.share_app_icon)
        activity.onOptionsItemSelected(menuItemShare)
    }
```

This is the code of OnOptionsItemSelected() true case state.

2021-07-10 18:43 UTC, Ayan-10 commented
@madhurgupta10 Sorry Actually `Utils.getScreenShot(rootView);` this line is invoking NullPointerException and internally 
`Bitmap.createBitmap(screenView.getDrawingCache());` this method creating the exception. Only 2 lines are left to cover.


```
java.lang.NullPointerException
	at org.robolectric.internal.bytecode.ShadowImpl.extract(ShadowImpl.java:14)
	at org.robolectric.shadow.api.Shadow.extract(Shadow.java:25)
	at org.robolectric.shadows.ShadowBitmap.createBitmap(ShadowBitmap.java:230)
	at android.graphics.Bitmap.createBitmap(Bitmap.java)
	at fr.free.nrw.commons.Utils.getScreenShot(Utils.java:181)
	at fr.free.nrw.commons.profile.ProfileActivity.onOptionsItemSelected(ProfileActivity.java:144)
	at fr.free.nrw.commons.profile.ProfileActivityTest.testOnOptionsItemSelected(ProfileActivityTest.kt:70)
```

2021-07-11 18:08 UTC, Ayan-10 commented
Solved the issue. 97% code coverage. Only one exception coverage left.

2021-07-13 21:47 UTC, madhurgupta10 commented
@Ayan-10 Very good job. 

For Exception Test, you can use `when-thenThrow` from Mockito

2021-07-13 21:48 UTC, madhurgupta10 requested changes

2021-07-13 21:48 UTC, madhurgupta10 commented on app/src/test/kotlin/fr/free/nrw/commons/profile/ProfileActivityTest.kt
> +        val menuItemShare: MenuItem = RoboMenuItem(R.id.share_app_icon)
It is a good idea to create separate test functions for each scenario

2021-07-14 07:51 UTC, Ayan-10 commented
@madhurgupta10 I am doing the same for throwing IOException. But every time I'm getting this 

```
org.mockito.exceptions.base.MockitoException: 
Checked exception is invalid for this method!
Invalid: java.io.IOException: IOException
```

I am trying to resolve it.

2021-07-15 11:34 UTC, Ayan-10 commented
@madhurgupta10 Mockito is not throwing IOException. I tried a lot but I can't find any way to throw IOException. It's throwing some other exceptions but not IOException. I am attaching the exception code. Can you please help me with this? I attached the Exception in the previous comment.

```
    @Test
    @Throws(Exception::class)
    fun testShareScreenException() {
        Shadows.shadowOf(Looper.getMainLooper()).idle()
        `when`(fileOutputStream.flush()).thenThrow(IOException("IOException"))
        val method: Method = ProfileActivity::class.java.getDeclaredMethod(
            "shareScreen"
        )
        method.isAccessible = true
        method.invoke(activity, bitmap)
    }

```

2021-07-17 00:09 UTC, madhurgupta10 commented
> @madhurgupta10 Mockito is not throwing IOException. I tried a lot but I can't find any way to throw IOException. It's throwing some other exceptions but not IOException. I am attaching the exception code. Can you please help me with this? I attached the Exception in the previous comment.
> 
> ```
>     @Test
>     @Throws(Exception::class)
>     fun testShareScreenException() {
>         Shadows.shadowOf(Looper.getMainLooper()).idle()
>         `when`(fileOutputStream.flush()).thenThrow(IOException("IOException"))
>         val method: Method = ProfileActivity::class.java.getDeclaredMethod(
>             "shareScreen"
>         )
>         method.isAccessible = true
>         method.invoke(activity, bitmap)
>     }
> ```

Your code looks good to me, not sure what could be the reason here. Anyways the current code coverage seems good. I am happy to merge this PR once you do the small change requested before :)

2021-07-18 00:10 UTC, madhurgupta10 approved these changes

2021-07-18 00:10 UTC, merged