#4730 - Nothing happens on clicking media in the Contribution tab of User's Profile
commons-app/apps-android-commons pull request #4736
Opened 2021-12-16 18:40 UTC by Pratham2305

**Description (required)**

Fixes #4730 

What changes did you make and why?

- Added ContributionFragment to the ViewPager instead of ContributionListFragment in Profile Activity

- Used the ContributionFragment similar to the way it used in Contribution Tab, to handle MediaDetailPagerFragment and ContributionListFragment transition.

- Disable unnecessary ContributionFragment features when it is used in ProfileActivity, like campaigns, nearby notification, etc.

- Added onBackPressed() method in ProfileActivity, and also replaced viewPager with ParentViewPager.

**Tests performed (required)**

Tested ProdDebug on Pixel 3 with API level 29.

2022-01-07 16:25 UTC, 4D17Y4 requested changes
Looks good to me, works well.
Just some documentation on the added function, variables and conditional statements.

Also, I think it would be better to have the top bar with bookmark, share, download options as in contribution and explore. @nicolas-raoul views ?

2022-01-18 15:05 UTC, neslihanturan requested changes
Other than my review, the code looks nice. Thanks a lot @Pratham2305 :)

2022-01-19 12:59 UTC, Pratham2305 commented on app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java
> +            isUserProfile = true;
Done!

2022-01-19 13:02 UTC, neslihanturan commented on app/src/main/java/fr/free/nrw/commons/profile/ProfileActivity.java
> +        if(contributionsFragment != null && contributionsFragment.getMediaDetailPagerFragment() != null && contributionsFragment.getMediaDetailPagerFragment().isVisible()) {
Maybe adding a comment to explain this if condition?

2022-01-19 13:06 UTC, neslihanturan commented on app/src/main/java/fr/free/nrw/commons/media/MediaDetailPagerFragment.java
> +        if (getActivity() instanceof ProfileActivity) {
adding some comment to explain this iftoo would be nice

2022-01-19 13:06 UTC, neslihanturan commented on app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java
> +            //((BaseActivity)getActivity()).getSupportActionBar().setDisplayHomeAsUpEnabled(false);
Removing this line and explaining the lines at the bottom would be cool

2022-01-19 13:08 UTC, neslihanturan requested changes
Some comments should be added and style issues should be fixed

2022-01-19 13:08 UTC, neslihanturan commented on app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java
> +            if(!isUserProfile) {
The if needs explanation comment

2022-04-18 13:17 UTC, neslihanturan approved these changes
Thanks a lot @Pratham2305 :)

2022-04-18 13:17 UTC, merged