Fixes 4539 : When Wikidata has no description Showing instance_of's label as a description
commons-app/apps-android-commons pull request #4799
Opened 2022-02-07 10:22 UTC by Ayan-10

**Description (required)**

Fixes #4539

What changes did you make and why?

Some Wikidata has no description. So, I used instance of Wikidata's label as a description.
While searching for Wikidata's created another call for getting labels of instance of Wikidatas and modified the Wikidata's description.

**Tests performed (required)**

Tested latest master ProdDebug on Pixel 3 with API level 30.

**Screenshots (for UI changes only)**

<img src="https://user-images.githubusercontent.com/71203077/152769615-43ccf75f-7793-423f-91d9-0190623e35cd.png" width=400/>

2022-02-07 10:38 UTC, Ayan-10 commented
@nicolas-raoul Hope it works. If it's working how about showing thumbnails in the same way?

2022-02-07 13:47 UTC, Ayan-10 commented
Thanks for the detailed explanation. I get the point.

2022-02-14 11:03 UTC, nicolas-raoul requested changes
Working great!
Would you mind adding unit tests to cover the uncovered parts?
Thanks!

2022-02-14 11:03 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/explore/depictions/DepictsClient.kt
> +                DepictedItem(entity,
Indentation is a bit off it seems.

2022-02-16 05:19 UTC, nicolas-raoul approved these changes

2022-02-16 05:19 UTC, merged