Fixed 4794 : Added a functionality of remembering zoom level on map
commons-app/apps-android-commons pull request #4817
Opened 2022-02-14 11:43 UTC by arinmodi

**Description (required)**

while selecting location in map during upload, remember the zoom level in addition of longitude & latitude. 

Fixes #4794

What changes did you make and why?
- Added new filed <b>zoomLevel</b> in <b>ImageCoordinates file</b> to store zoom level
- Storing the new key-value pair for <b>zoom level</b> in <b>LocationPickerActivity file</b>.
- Set the <b>zoom level</b> in <b>UploadMediaDetailFragment</b> also updating the zoom level in same file.

**Tests performed**

Tested build variant on ASUS_X00TD with API level 28.

2022-02-14 16:09 UTC, arinmodi commented
Hey @nicolas-raoul, Could you please review this ?

2022-02-15 01:10 UTC, nicolas-raoul requested changes

2022-02-15 01:10 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/LocationPicker/LocationPickerActivity.java
> +            applicationKvStore.putString(LAST_ZOOM,mapboxMap.getCameraPosition().zoom + "");
Minor: In Java we always put a space after `,`

2022-02-15 01:10 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java
> +                    .zoom(defaultZoom).build())
Please add a unit test covering this line, thanks!

2022-02-15 01:10 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java
> +                defaultZoom = Double.parseDouble(defaultKvStore.getString(LAST_ZOOM));
Please add a unit test covering this line, thanks!

2022-02-15 03:00 UTC, nicolas-raoul reviewed
By the way, I just tested, it works great :-)

2022-02-15 08:21 UTC, arinmodi commented
Thanks @nicolas-raoul

2022-02-15 13:04 UTC, arinmodi commented
@nicolas-raoul, can you suggest me any tutorial for adding test, i new to writing unit test

2022-02-15 13:38 UTC, nicolas-raoul commented
Here is a tutorial: https://www.vogella.com/tutorials/Mockito/article.html
You should also look at example unit tests within the app: https://github.com/commons-app/apps-android-commons/tree/master/app/src/test/kotlin/fr/free/nrw/commons

2022-02-15 13:42 UTC, arinmodi commented
how can I add test for the defaultKvStore ? I tried to find it in other tests but not helped much

2022-02-15 16:30 UTC, arinmodi commented
Hey @nicolas-raoul, I added the changes, but the tests which i wrote might not be perfect but it is passing,

2022-02-15 18:49 UTC, arinmodi commented
@nicolas-raoul, please check that did i wrote the test in right way ?

2022-02-16 03:48 UTC, nicolas-raoul requested changes

2022-02-16 03:48 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/LocationPicker/LocationPickerActivity.java
> +            applicationKvStore.putString(LAST_ZOOM, mapboxMap.getCameraPosition().zoom + "");
It looks like this line is not covered by the unit tests.

2022-02-16 03:48 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java
> +            defaultZoom = uploadItem.getGpsCoords().getZoomLevel();
It looks like this line is not covered by the unit tests.

2022-02-16 03:48 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java
> +                    .zoom(defaultZoom).build())
It looks like this line is not covered by the unit tests.

2022-02-16 03:48 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java
> +                defaultZoom = Double.parseDouble(defaultKvStore.getString(LAST_ZOOM));
It looks like this line is not covered by the unit tests.

2022-02-16 20:28 UTC, arinmodi commented
Hey @nicolas-raoul, please don't review new changes right now, i will push the new changes tomorrow once i solved the mapbox configuration error

2022-02-17 06:47 UTC, arinmodi commented
Hey @nicolas-raoul, I wrote the required test for defaulzoom, please review this

2022-02-17 06:52 UTC, nicolas-raoul approved these changes

2022-02-17 06:52 UTC, merged