Unit Tests for LocationPickerActivity
commons-app/apps-android-commons pull request #4830
Opened 2022-02-17 15:47 UTC by Ayan-10

**Description (required)**

Added unit tests for LocationPickerActivity

2022-02-18 04:35 UTC, madhurgupta10 commented
> ```
> fr.free.nrw.commons.navtab.MoreBottomSheetLoggedOutFragmentUnitTests > testOnFeedbackClicked FAILED
>     java.lang.IllegalStateException at MoreBottomSheetLoggedOutFragmentUnitTests.kt:66
> ```
> 
> @madhurgupta10 I think this build failure doesn't belong to this PR.

@Ayan-10 Yes, I have triggered the job again. This is a known issue, not sure what causes it but sometimes this test fails.

2022-02-18 04:42 UTC, madhurgupta10 requested changes

2022-02-18 04:42 UTC, madhurgupta10 commented on app/src/test/kotlin/fr/free/nrw/commons/locationpicker/LocationPickerActivityUnitTests.kt
> +    fun testBindListeners() {
Add verification to this tests for `mapboxMap`

2022-02-18 04:42 UTC, madhurgupta10 commented on app/src/test/kotlin/fr/free/nrw/commons/locationpicker/LocationPickerActivityUnitTests.kt
> +    fun testOnChanged() {
Add verification to this tests for mapboxMap

2022-02-18 04:42 UTC, madhurgupta10 commented on app/src/test/kotlin/fr/free/nrw/commons/locationpicker/LocationPickerActivityUnitTests.kt
> +    fun testOnMapReady() {
You can refactor your lambda block inside `onMapReady`  to a new function and write additional tests to cover those lines

2022-02-18 04:43 UTC, madhurgupta10 commented
@Ayan-10 also, please sync your branch with the latest master to compare with the most recent code coverage.

2022-02-18 15:47 UTC, madhurgupta10 commented
> ```
> droppedMarkerLayer.setProperties(
>     visibility: none
> );
> -> at com.mapbox.mapboxsdk.style.layers.Layer.setProperties(Layer.java:47)
> Actual invocation has different arguments:
> droppedMarkerLayer.setProperties(
>     visibility: none
> );
> ```
> 
> Getting this error while verifying `droppedMarkerLayer`. Although the actual and wanted arguments are the same as you can see in the error.
> 
> The if part of onStyleLoaded is showing `Thread is not initialized ` error on `GeoJsonSource("dropped-marker-source-id")`.

Different objects are compared even though they carry same value. Try `verify(yourMock).yourMethod(any())

2022-02-18 16:15 UTC, Ayan-10 commented
`droppedMarkerLayer` is verified now.

Thanks, @madhurgupta10

2022-02-19 08:29 UTC, madhurgupta10 commented
@Ayan-10 `24.69%` coverage for Location Picker Activity is decent but try to get it around 80+

2022-02-20 05:43 UTC, Ayan-10 commented
@madhurgupta10 I tried my best to cover more lines. But hardly 20-25 more lines can be covered if I refactor some lines from `onCreate` and some methods but 80+ will be possible and the reason is static and final methods/members. Mocikto is behaving unexpectedly while mocking static/final members compared to others. Most of the lines are uncovered because of this. Also, I was doing `whenever(activity.findViewById(R.id.string))` but it's not triggering the `findViewById` in LocationPickerActivity.

2022-02-20 06:06 UTC, madhurgupta10 approved these changes
I am happy to merge these tests, you can try with Instrumentation tests after https://github.com/commons-app/apps-android-commons/pull/4832 is merged to reach the 80% target

2022-02-20 06:07 UTC, merged

2022-02-20 09:18 UTC, madhurgupta10 commented
@Ayan-10 These methods would be easy to test using mockito
![image](https://user-images.githubusercontent.com/30932899/154836071-fc7bb24e-b529-4db0-beea-8503713cd533.png)

2022-02-20 10:00 UTC, Ayan-10 commented
@madhurgupta10 I tried to test those before but got `Caused by: java.lang.IllegalStateException: No activity` error I thought the error is occurring because of not calling `.create` while creating the activity.

2022-02-20 10:29 UTC, madhurgupta10 commented
> @madhurgupta10 I tried to test those before but got `Caused by: java.lang.IllegalStateException: No activity` error I thought the error is occurring because of not calling `.create` while creating the activity.

You can update the activity to an instance of MainActivity during those tests.

2022-02-20 13:30 UTC, Ayan-10 commented
> You can update the activity to an instance of MainActivity during those tests.

If I update the activity as a MainActivity during those tests, then I think methods of MainActivity will be covered instead of LocationPickerActivity. Isn't it?


I was thinking the same error will occur for every method but all errors of those methods are not the same and `onLowMemory` can be tested. **So I added the test for `onLowMemory`** and also attached all the errors.

**onDestroy, onSaveInstanceState and onStart**
```
Caused by: java.lang.IllegalStateException: FragmentManager has been destroyed
	at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1781)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1841)
	at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:2599)
	at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:330)
	at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:365)
	at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:233)
	at fr.free.nrw.commons.theme.BaseActivity.onDestroy(BaseActivity.java:50)
	at fr.free.nrw.commons.LocationPicker.LocationPickerActivity.onDestroy(LocationPickerActivity.java:441)
```

**onStop and onPause**
```
Caused by: java.lang.IllegalStateException: No activity
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1484)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2617)
	at androidx.fragment.app.FragmentManager.dispatchPause(FragmentManager.java:2585)
	at androidx.fragment.app.FragmentController.dispatchPause(FragmentController.java:280)
	at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:419)
	at fr.free.nrw.commons.LocationPicker.LocationPickerActivity.onPause(LocationPickerActivity.java:423)

```
**onResume**
```
Caused by: java.lang.NullPointerException
	at fr.free.nrw.commons.theme.BaseActivity.onResume(BaseActivity.java:41)
	at fr.free.nrw.commons.LocationPicker.LocationPickerActivity.onResume(LocationPickerActivity.java:417)

```

2022-02-20 13:46 UTC, madhurgupta10 commented
Correct, maybe then instrumentation tests is the only option here.