Fixed #4793 : Remove the need to tap "Next" again
commons-app/apps-android-commons pull request #4833
Opened 2022-02-18 11:03 UTC by arinmodi

**Description**
- After tapping "Next", the "No location found" popup appears.

- Problem: After choosing a location, I am still at the caption/description step, so I have to tap "Next" again.

- Goal: After choosing a location, I should be sent directly to the next step (depictions, or next media in the case of a multi-upload)

Fixes #4793

What changes did you make and why?

-  when <b>add location dialog</b> appears, flag become true and once the user selected the location they will redirect to the next screen and flag become false 

- Also add and update the required test

Tests performed

Tested on ASUS_X00TD with API level 28.

2022-02-18 11:04 UTC, arinmodi commented
@nicolas-raoul, please review this....

2022-02-18 13:48 UTC, arinmodi commented
Hey @nicolas-raoul, is there any changes required ?

2022-02-19 00:26 UTC, nicolas-raoul requested changes
It works thanks!

2022-02-19 00:26 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java
> +    public boolean isNoLocationDialog;
javadoc

2022-02-19 00:26 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java
> +                if(isNoLocationDialog){
please add comment to explain what is being done

2022-02-19 06:05 UTC, nicolas-raoul requested changes

2022-02-19 06:55 UTC, arinmodi commented
@nicolas-raoul, added the requested changes

2022-02-19 07:44 UTC, nicolas-raoul approved these changes

2022-02-19 07:44 UTC, merged