Fixed #4784 : Inform users about unsupported features in beta flavor
commons-app/apps-android-commons pull request #4834
Opened 2022-02-18 20:03 UTC by KosOrKosm

### **Description**

Fixes #4784 

### **What changes did you make and why?**

The app is receiving empty results or HTTP 500 responses when trying to retrieve the leaderboard or achievements for users in the Beta environment.

Added a toast that appears whenever AchievementsFragment or LeaderboardFragment is made visible on Beta flavors, informing the user these features are unavailable in Beta flavor. Also skips the dysfunctional API calls and hides the empty / dysfunctional UI elements.

### **Tests performed**

Tested betaDebug + prodDebug on Pixel 3a (AVD Emulator) with API level 28.

### **Screenshots**

![image](https://user-images.githubusercontent.com/46112489/154745678-048e9d16-aac2-47a4-9aaa-6361851c9811.png) ![image](https://user-images.githubusercontent.com/46112489/154745719-f54d43b1-0149-4252-acc0-2a1914e81932.png)

2022-02-19 08:41 UTC, madhurgupta10 requested changes

2022-02-19 08:41 UTC, madhurgupta10 commented on app/src/test/kotlin/fr/free/nrw/commons/leaderboard/LeaderboardFragmentUnitTests.kt
> +    fun testMenuVisibilityOverrideNoContext() {
You can add assert equals here to check if Toast contains the right text

```
Assert.assertEquals(ShadowToast.getTextOfLatestToast().toString(), getString(R.string.leaderboard_unavailable_beta))
```

2022-02-19 08:41 UTC, madhurgupta10 commented on app/src/test/kotlin/fr/free/nrw/commons/profile/achievements/AchievementsFragmentUnitTests.kt
> +    fun testMenuVisibilityOverrideNoContext() {
Similar to other test function add asset for toast string

2022-02-19 08:41 UTC, madhurgupta10 commented on app/src/main/java/fr/free/nrw/commons/profile/leaderboard/LeaderboardFragment.java
> +        if(ConfigUtils.isBetaFlavour() && visible && getContext() != null) {
Add test when false is passed as the argument, in that case toast should not appear

2022-02-19 08:41 UTC, madhurgupta10 commented on app/src/main/java/fr/free/nrw/commons/profile/achievements/AchievementsFragment.java
> +    public void setMenuVisibility(boolean visible) {
Add test when false is passed as the argument, in that case toast should not appear

2022-02-19 08:47 UTC, madhurgupta10 commented
@KosOrKosm Could you also sync your branch with the latest master?

2022-02-19 21:45 UTC, KosOrKosm commented
@madhurgupta10 Synced with master and updated tests to check if the Toast appears.

2022-02-20 06:36 UTC, madhurgupta10 approved these changes
Haven't tested but the changes looks good to me.

2022-02-22 17:52 UTC, KosOrKosm commented
Hello @nicolas-raoul, could you review/test my PR?

2022-02-23 07:46 UTC, nicolas-raoul commented
Sorry for the delay!
Strangely at the moment I am struggling to get the beta flavor to run:
```
$ ./gradlew installBetaDebug
[...]
Installing APK 'app-commons-v3.1.1-KosOrKosm-beta-disable-prod-only-apis-beta-debug.apk' on 'SM-G970F - 9' for app:betaDebug
Installed on 1 device.
[...]
BUILD SUCCESSFUL in 3m 10s
$ adb shell am start -n fr.free.nrw.commons/fr.free.nrw.commonsCommonsApplication
Starting: Intent { cmp=fr.free.nrw.commons/fr.free.nrw.commonsCommonsApplication }
Error type 3
Error: Activity class {fr.free.nrw.commons/fr.free.nrw.commonsCommonsApplication} does not exist.
```
Any idea what might be wrong, by any chance? :-)

2022-02-23 07:51 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/profile/achievements/AchievementsFragment.java
> +            return rootView;
Would it be possible to add a unit test covering these lines?

2022-02-23 08:32 UTC, nicolas-raoul commented
Pushing the APK and installing it directly worked, strange...

Anyway, I tested and it is working great! :-)

Would you mind just addressing my previous coverage comment?
Thanks!

2022-02-24 05:24 UTC, KosOrKosm commented
@nicolas-raoul I added a test that should cover the missing lines in AchievementsFragment

2022-02-24 05:40 UTC, nicolas-raoul approved these changes

2022-02-24 05:40 UTC, merged

2022-03-11 13:55 UTC, nicolas-raoul commented
This pull request unfortunately broke some unit tests:
```
fr.free.nrw.commons.leaderboard.LeaderboardFragmentUnitTests > testMenuVisibilityOverrideVisibleWithContext FAILED
    java.lang.Exception at AndroidTestEnvironment.java:538
        Caused by: java.lang.NullPointerException at LeaderboardFragmentUnitTests.kt:232

fr.free.nrw.commons.profile.achievements.AchievementsFragmentUnitTests > testMenuVisibilityOverrideVisibleWithContext FAILED
    java.lang.Exception at AndroidTestEnvironment.java:538
        Caused by: java.lang.NullPointerException at AchievementsFragmentUnitTests.kt:375
```

2022-03-11 17:27 UTC, KosOrKosm commented
That's odd, the tests pass in my local environment. I think the test might be failing on production because of the beta flavor check, which causes the test to never display a Toast and the assertion to fail. Is there any way to overwrite the build flavor for the duration of a test?

2022-03-11 17:49 UTC, madhurgupta10 commented
> This pull request unfortunately broke some unit tests:
> 
> ```
> fr.free.nrw.commons.leaderboard.LeaderboardFragmentUnitTests > testMenuVisibilityOverrideVisibleWithContext FAILED
>     java.lang.Exception at AndroidTestEnvironment.java:538
>         Caused by: java.lang.NullPointerException at LeaderboardFragmentUnitTests.kt:232
> 
> fr.free.nrw.commons.profile.achievements.AchievementsFragmentUnitTests > testMenuVisibilityOverrideVisibleWithContext FAILED
>     java.lang.Exception at AndroidTestEnvironment.java:538
>         Caused by: java.lang.NullPointerException at AchievementsFragmentUnitTests.kt:375
> ```

The latest build (https://github.com/commons-app/apps-android-commons/runs/5512038434?check_suite_focus=true) seems to be successful without any failing tests, @nicolas-raoul can you please confirm when you detected these failing tests?

2022-03-19 14:08 UTC, nicolas-raoul commented
@madhurgupta10 I had found this commit using `git bissect` running `./gradlew testProdDebugUnitTest`, but I might have messed up something. Anyway master tests are passing now, thanks all! :-)