Refactor: Category model
commons-app/apps-android-commons pull request #4853
Opened 2022-02-25 09:59 UTC by ben-mathu

Part of an ongoing code refactoring to move all models to a common models package.

Fixes #4782

Moved Category model to data.models package.

Tested debug on Pixel 4 (Emulator) with API level 30.

2022-04-28 14:39 UTC, neslihanturan requested changes

2022-04-28 14:39 UTC, neslihanturan commented on app/src/main/java/fr/free/nrw/commons/category/CategoriesModel.kt
> +import fr.free.nrw.commons.category.models.Category
Well, this is also a model class. Shouldn't we also put this into the model package too? @ben-mathu

2022-05-05 07:14 UTC, neslihanturan commented
Hi, is this PR sleeping @ben-mathu ?:)

2024-03-16 00:24 UTC, psh commented
Closing: 2 years old and looks abandoned.

2024-03-16 00:24 UTC, closed without merging