Fixed - #4844 : In peer review, deletion proposal is sent even if no reason is chosen
commons-app/apps-android-commons pull request #4862
Opened 2022-02-27 12:48 UTC by arinmodi

Description

Bug : In peer review, the deletion proposal is sent even if no reason is chosen.

Fixes #4844

What changes did you make and why?

Just add the if condition for checking the selected reasons

Tests performed

Tested build variant on ASUS_X00TD with API level 28

2022-02-27 13:13 UTC, arinmodi commented
@nicolas-raoul, please review this...

2022-02-27 16:49 UTC, devarsh-mavani-19 commented
Review by student

Before 

https://user-images.githubusercontent.com/55136047/155891462-a429c97d-90d7-48da-a9b1-02a6a0191343.mp4

After

https://user-images.githubusercontent.com/55136047/155891475-b82b037f-c404-4ce5-9c1b-2ab0ccbfd0a2.mp4


Issue Solved

2022-02-27 17:47 UTC, 4D17Y4 reviewed
Looks good to me.
Just some minor changes.  
Thanks for the student review @devarsh-mavani-19.

2022-02-27 17:47 UTC, 4D17Y4 commented on app/src/main/java/fr/free/nrw/commons/delete/DeleteHelper.java
> +            }else{
Add a comment "No reason selected"

2022-02-27 17:47 UTC, 4D17Y4 commented on app/src/main/java/fr/free/nrw/commons/delete/DeleteHelper.java
> +            if(mUserReason.size() > 0){
You can use isEmpty method.

2022-02-27 17:47 UTC, 4D17Y4 commented on app/src/main/res/values/strings.xml
> +  <string name="select_one_reason">Please, Select At-least one reason</string>
`Please select at least one reason.`

Also the name of the string could be "no_reason_selected"

2022-02-28 05:08 UTC, arinmodi commented
Hey @4D17Y4, i have done the changes

2022-02-28 05:08 UTC, arinmodi commented
@nicolas-raoul, please review this

2022-02-28 07:42 UTC, 4D17Y4 reviewed
Minor fixes.

2022-02-28 07:42 UTC, 4D17Y4 commented on app/src/main/java/fr/free/nrw/commons/delete/DeleteHelper.java
> +            if(mUserReason.isEmpty()){
not empty ( == false ) right ?
This condition handles the non empty case.

2022-02-28 07:42 UTC, 4D17Y4 commented on app/src/main/res/values/strings.xml
> +  <string name="no_reason_selected">Please select at least one reason</string>
period at the end.

2022-02-28 07:52 UTC, arinmodi commented
@4D17Y4 sorry i forget to add not operator, now it's fixed

2022-02-28 09:45 UTC, arinmodi commented
Hey @4D17Y4, not able to login into beta version, it is saying timeout, what should i do ?

2022-02-28 19:47 UTC, 4D17Y4 commented
I just tried it, I can log in to beta. 
Might be an issue with your network, check your network in case that's the problem.
If you are still not able to login, it maybe a server issue. I would suggest wait for a day or two before trying again.

2022-02-28 19:50 UTC, 4D17Y4 commented
Looks good to me. 
@nicolas-raoul any final edits ?

2022-03-01 07:29 UTC, arinmodi commented
@nicolas-raoul, please look into this...

2022-03-01 14:07 UTC, arinmodi commented
Yes, that would be nice idea and also we can add one more thing that if the user is still pressed the ok button even if disable than we can display popUp also.

What do you think ?

2022-03-01 18:17 UTC, arinmodi commented
Hey @nicolas-raoul, is there any callback for the changes in the list of selected reasons, we can set the button disable initially but we can't change it afterwards cause we don't have any listener for the changes in choices, what should i do ?

2022-03-02 10:53 UTC, arinmodi commented
Hey @nicolas-raoul, please update on this, thanks

2022-03-02 12:34 UTC, nicolas-raoul commented
> Yes, that would be nice idea and also we can add one more thing that if the user is still pressed the ok button even if disable than we can display popUp also.

Good idea!

> we can set the button disable initially but we can't change it afterwards cause we don't have any listener for the changes in choices

Not sure what is the best solution but listening sounds doable... you will have to look for code examples on the Internet and try, good luck!

2022-03-02 17:39 UTC, arinmodi commented
Hey @nicolas-raoul, added the required changes as you idea but not implemented my idea because we can't listen for the button event once we disable it, Thanks

2022-03-03 05:50 UTC, 4D17Y4 commented
U can try `setOnCheckedChangeListener` on the checkbox. Or onclicklistener with some checks.

2022-03-03 11:10 UTC, nicolas-raoul requested changes
The code looks good to me!
Would you mind add unit tests?

2022-03-03 16:04 UTC, arinmodi commented
@nicolas-raoul, Unit is already there for deleteHelper class

2022-03-03 18:24 UTC, arinmodi commented
Hey @nicolas-raoul, added the required test, please review this

2022-03-04 03:31 UTC, arinmodi commented
@nicolas-raoul, pushed some minor fixes to the code, please review this

2022-03-07 08:02 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/delete/DeleteHelper.java
> -                    makeDeletion(context, media, finalReason))
If I understand correctly, only the indentation was changed for this block. If you actually changed code, please let me know.
That makes the code coverage check ignorable.

2022-03-07 08:08 UTC, arinmodi commented
Yes, only indentation is changed, should i undo that ?

2022-03-07 08:50 UTC, nicolas-raoul commented
It is usually better to address each concern in a different PR. No need to undo here though.

2022-03-07 08:51 UTC, nicolas-raoul approved these changes
Looks good, thanks!

2022-03-07 08:52 UTC, merged