Fixes #4589 :- The empty screen while no images found in custom picture selector
commons-app/apps-android-commons pull request #4863
Opened 2022-02-28 07:01 UTC by Rishavgupta12345

The empty screen while no images found in custom picture selector #4589  is fixed now

I was solving this issue in the Image fragment as mentioned by @4D17Y4  but it created a few unwanted bugs so I have to delete my previous pull request, I created a new one with a different approach and I as this is working perfectly so, for now, this can be an ideal solution 

@nicolas-raoul  screenshots added 

No image found
![Screenshot 2022-02-28 123014](https://user-images.githubusercontent.com/74723804/155938516-611007ee-5ddd-4636-9379-f93abf4b2c36.png)

Image found
![Screenshot 2022-02-28 122831](https://user-images.githubusercontent.com/74723804/155938559-0ffc4a1a-0c24-425d-8170-befc7eb149b4.png)

2022-02-28 11:34 UTC, arinmodi commented
Review by student

- Before the Changes : 

https://user-images.githubusercontent.com/61725413/155976238-f773f7dc-9111-4b36-86d3-b3f929b8ff3c.mp4

- After the Changes : 

https://user-images.githubusercontent.com/61725413/155976309-dc2022fc-83f3-47d8-bf47-5d2a8903a3e3.mp4

<br/><br/>

Status : <b>issue solved</b>

2022-02-28 12:13 UTC, Rishavgupta12345 commented
> Review by student
> 
> * Before the Changes :
> 
>  before.mp4 
> * After the Changes :
> 
>  after.mp4 
> Status : issue solved

thanks a lot for the review

2022-03-02 12:30 UTC, nicolas-raoul requested changes
Wonderful! Thanks for adding javadoc.
Just a few requests added.

And thanks Arin for the review!

2022-03-02 12:30 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/customselector/ui/selector/CustomSelectorActivity.kt
> +            val linearLayout: LinearLayout = findViewById<View>(R.id.linear_layout_noimage) as LinearLayout
Unit test for this block

2022-03-02 12:30 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/customselector/ui/selector/CustomSelectorActivity.kt
> +            val projection = arrayOf(MediaStore.Images.Media._ID)
Unit test for this block

2022-03-02 12:50 UTC, 4D17Y4 commented
Hey @Rishavgupta12345, 
Seems like u have reverted to your previous approach. Any reasons ?
You mentioned unwanted bugs, would be nice if you could list them. I am sure we can figure out those. 

The basic reason why we don't want to go with this approach is that it queries images again which is inefficient as we are just concerned with the number of images returned. Furthermore I can see that "no image" text is visible but the progress bar is still visible. Therefore I suggested to handle this in the results function. On a plus point all the test are done on the custom selector functions, major changes wont be necessary.

2022-03-02 13:33 UTC, 4D17Y4 commented
@Rishavgupta12345 you can try again if you want. I'll unassign the issue so that others can work on it. In case you plan to work on it again you can ping us to assign you.

2022-03-02 13:42 UTC, Rishavgupta12345 commented
> @Rishavgupta12345 you can try again if you want. I'll unassign the issue for now so that others can work on it. In case you plan to work on it again you can ping us to get assigned.

don't un assign me I will work on it

2022-03-04 14:50 UTC, Rishavgupta12345 commented
> > Hey @Rishavgupta12345, Seems like u have reverted to your previous approach. Any reasons ? You mentioned unwanted bugs, would be nice if you could list them. I am sure we can figure out those.
> > The basic reason why we don't want to go with this approach is that it queries images again which is inefficient as we are just concerned with the number of images returned. So I suggested to handle this in the results function. On a plus point all the test are done on the custom selector functions, major changes wont be necessary.
> 
> I am not getting the perfect way of implementing it on Image fragments, because there I tried some approaches and they are not working as they should

@4D17Y4 If I am making this in image and folder fragment then can I make another function isImageGalleryEmpty() and call them inside the handleResult() funtion? like I did in this pull request

2022-03-04 16:28 UTC, 4D17Y4 commented
Yes you can do that. This time you don't have to query for the images.

2022-03-05 05:45 UTC, Rishavgupta12345 commented
> Yes you can do that. This time you don't have to query for the images.

@4D17Y4 @nicolas-raoul  finally done in best possible way. Ready to merge

2022-03-05 15:12 UTC, 4D17Y4 requested changes
Best approach indeed. 
Nice work. 
Just some minor changes.

2022-03-05 15:12 UTC, 4D17Y4 commented on app/src/main/res/layout/fragment_custom_selector.xml
> -    android:visibility="gone"
Make visibility as `gone` in initial state and make it visible if there are no images. It is visible even when the loader is active.

2022-03-05 15:12 UTC, 4D17Y4 commented on app/src/main/java/fr/free/nrw/commons/customselector/ui/selector/FolderFragment.kt
> +        if(images.isNotEmpty())
Inside the callbackstatus condition.

2022-03-06 06:43 UTC, Rishavgupta12345 commented on app/src/main/java/fr/free/nrw/commons/customselector/ui/selector/FolderFragment.kt
> +        if(images.isNotEmpty())
done

2022-03-06 06:44 UTC, Rishavgupta12345 commented
> Best approach indeed. Nice work. Just some minor changes.

@4D17Y4 done the requested changes

2022-03-07 09:30 UTC, 4D17Y4 commented
Works. 
Good to merge.
Any final edits @nicolas-raoul ?

2022-03-07 09:33 UTC, nicolas-raoul approved these changes

2022-03-07 09:34 UTC, merged

2022-03-07 10:09 UTC, madhurgupta10 commented
@Rishavgupta12345 It seems like 2 of the tests are failing after this PR was merged, can you take a look into it, please?
```
fr.free.nrw.commons.customselector.ui.selector.ImageFragmentTest > testHandleResult FAILED
    java.lang.Exception at AndroidTestEnvironment.java:538
        Caused by: java.lang.reflect.InvocationTargetException at ImageFragmentTest.kt:128
            Caused by: java.lang.NullPointerException at ImageFragmentTest.kt:128

fr.free.nrw.commons.customselector.ui.selector.FolderFragmentTest > testHandleResult FAILED
    java.lang.Exception at AndroidTestEnvironment.java:538
        Caused by: java.lang.reflect.InvocationTargetException at FolderFragmentTest.kt:128
            Caused by: java.lang.NullPointerException at FolderFragmentTest.kt:128
```

2022-03-07 15:04 UTC, Rishavgupta12345 commented
> @Rishavgupta12345 It seems like 2 of the tests are failing after this PR was merged, can you take a look into it, please?
> 
> ```
> fr.free.nrw.commons.customselector.ui.selector.ImageFragmentTest > testHandleResult FAILED
>     java.lang.Exception at AndroidTestEnvironment.java:538
>         Caused by: java.lang.reflect.InvocationTargetException at ImageFragmentTest.kt:128
>             Caused by: java.lang.NullPointerException at ImageFragmentTest.kt:128
> 
> fr.free.nrw.commons.customselector.ui.selector.FolderFragmentTest > testHandleResult FAILED
>     java.lang.Exception at AndroidTestEnvironment.java:538
>         Caused by: java.lang.reflect.InvocationTargetException at FolderFragmentTest.kt:128
>             Caused by: java.lang.NullPointerException at FolderFragmentTest.kt:128
> ```

I have never faced any issue like this before , so can you please guide me what should I do now ? 

BY my knowledge i think I have to make some changes in the tests as new things were added which doesn't have tests on it

2022-03-07 16:06 UTC, madhurgupta10 commented
You can run the tests locally from Android Studio and see the logs why they are failing and update the tests accordingly.

2022-03-09 03:12 UTC, Rishavgupta12345 commented
> @Rishavgupta12345 can you prioritise this issue over others for the time, build fails make it difficult for us to review PRs.

okay

2022-03-09 06:47 UTC, Rishavgupta12345 commented
> @Rishavgupta12345 can you prioritise this issue over others for the time, build fails make it difficult for us to review PRs.

@madhurgupta10 I have done the changes, but how should I commit? I have committed the changes in this branch but it didn't get committed because this is already merged, so how should I commit now?