Refactor: media models
commons-app/apps-android-commons pull request #4864
Opened 2022-02-28 07:42 UTC by ben-mathu

Part of an ongoing code refactoring to move all models to a common models package.

Fixes #4782

Moved media models to data.models package.

Tested debug on Pixel 4 (Emulator) with API level 30.

2022-04-28 15:17 UTC, neslihanturan requested changes

2022-04-28 15:17 UTC, neslihanturan commented on app/src/main/java/fr/free/nrw/commons/MediaDataExtractor.kt
> +import fr.free.nrw.commons.media.media.IdAndCaptions
did you meant media.models instead of media.media? @ben-mathu

2022-05-05 07:14 UTC, neslihanturan commented
Hi, is this PR sleeping @ben-mathu ?:)

2024-03-16 00:26 UTC, psh commented
Closing: 2 years old and looks abandoned.

2024-03-16 00:26 UTC, closed without merging