Rafactor main
commons-app/apps-android-commons pull request #4872
Opened 2022-02-28 14:18 UTC by ben-mathu

Part of an ongoing code refactoring to move all models to a common models package.

Fixes #4782

Moved main models to data.models package.

Tested debug on Pixel 4 (Emulator) with API level 30.

2022-03-01 13:49 UTC, Rishavgupta12345 commented
contributor review:-

why are you making so many pull requests, you are solving a single issue which is #4782 in parts so make a single branch and merge all your commits in one pull request, it's better than flooding the repository with tons of pull requests. Just keep the repository clean.

2022-03-01 15:25 UTC, ben-mathu commented
> Thanks, @ben-mathu Please do make multiple PRs for this issue. Ideally one per package.

This is what I understood from your comment above in issue: #4782 [here](https://github.com/commons-app/apps-android-commons/issues/4782#issuecomment-1049059968)

2022-05-19 13:06 UTC, ben-mathu commented
@madhurgupta10 please review

2022-06-01 15:08 UTC, neslihanturan commented on .idea/codeStyles/Project.xml
> -<component name="ProjectCodeStyleConfiguration">
this file shouldnt be edited

2022-06-01 15:12 UTC, neslihanturan requested changes
Thanks a lot @ben-mathu , there are irrelevant edits in this PR. You can always check files changes from github UI to make sure your PR has only needed changes. You can also use git status before adding your changes to your commits to prevent this. Please include only relevant changes.

Also there are empty .jpg files and they are not wanted.

2024-03-16 00:27 UTC, psh commented
Closing: 2 years old and looks abandoned.

2024-03-16 00:27 UTC, closed without merging