Stop filtering out all categories that have a year in it
commons-app/apps-android-commons pull request #4902
Opened 2022-03-19 12:08 UTC by sivaraam

**Description (required)**

Fixes #4901 

What changes did you make and why?

Made the conditional tighter so that it only checks for the cases needed by #750 and not more than that.

**Tests performed (required)**

Tested ProdDebug on Nexus 4 emulator with API level 30.

2022-03-19 12:59 UTC, nicolas-raoul reviewed
I think this feature would graetly benefit from a unit test :-)
- `Photographs taken on 2015-11-08` -> Hide
- `Amavenita (ship, 2014)` -> Do not hide

2022-03-19 14:23 UTC, sivaraam commented
> I think this feature would greatly benefit from a unit test :-)

Good point. I'll look into adding the tests. I must mention that I'm not so used to adding unit tests for Android. So, it might take me some time. I'll update here once I'm done with adding the required tests.

2022-03-19 19:04 UTC, sivaraam commented
Just wanted to update here regarding the test. I was trying to [cook up a test](https://github.com/sivaraam/apps-android-commons/blob/ks/4901-fix-tests/app/src/test/kotlin/fr/free/nrw/commons/upload/CategoriesPresenterTest.kt#L102-L137) for the mentioned case but somehow the test [keeps failing](https://github.com/sivaraam/apps-android-commons/runs/5612941346?check_suite_focus=true). I think I'll need to look more deeply to write the test properly. Meanwhile, if anyone has any good pointers on what I'm getting wrong, do let me know.

2022-03-20 18:06 UTC, devarsh-mavani-19 commented
> 

Hey I think the **checkIrrelevantCategoryIsFilteredOut** should be inside categories presenter test class. 
Please check the below code I think it tests the functionality of filtering out well
```
        doReturn(Observable.just<List<CategoryItem>>(
            listOf(CategoryItem("taken on 2014", "Desc", "Thumb", false)
                ,CategoryItem("test 2014", "Desc", "Thumb", false)
                ,CategoryItem("japan in 660s", "Desc", "Thumb", false))))
            .`when`(repository).searchAll(ArgumentMatchers.anyString()
                , ArgumentMatchers.any(), ArgumentMatchers.any())

        `when`(repository.containsYear(anyString())).thenCallRealMethod()

        val categoriesModel = Mockito.mock(CategoriesModel::class.java)
        `when`(categoriesModel.containsYear(anyString())).thenCallRealMethod()
        Whitebox.setInternalState(repository, "categoriesModel", categoriesModel)

        repository.searchAll(ArgumentMatchers.anyString()
            , ArgumentMatchers.any(), ArgumentMatchers.any())
            .map { it.filterNot { categoryItem -> repository.containsYear(categoryItem.name) } }
            .test()
            .assertValue(listOf(CategoryItem("test 2014", "Desc", "Thumb", false)))

```

2023-04-19 07:25 UTC, shankarpriyank commented
I might be totally wrong, but I think we can test the functionality using simpler unit tests like these
```
  @Test
    fun testCheckIrrelevantCategoryIsFilteredOut() {
        assertFalse(containsYear("Category:Media needing categories as of 16 June 2017"))
    }

@Test
    fun testCheckNotAllCategoriesWithDateAreFilteredOut() {
        assertTrue(containsYear("Category:Amavenita (ship, 2014)"))
    }

```

2024-08-01 01:57 UTC, mnalis commented
@sivaraam as mentioned in https://github.com/commons-app/apps-android-commons/issues/5749#issuecomment-2227279839 as other prerequisites have been merged now; perhaps this PR can now be rebased to latest master and updated to allow years (except blacklisted ones)?

2024-12-14 10:14 UTC, nicolas-raoul requested changes
Can anyone merge the conflict? Thanks!

2024-12-27 12:36 UTC, parneet-guraya commented
I can try updating it :-)

2024-12-27 15:04 UTC, nicolas-raoul commented
@parneet-guraya Would you mind asking at #4901 so that I can assign you to it? GitHub does not let me assign people who have not commented. Thanks! :-)

2024-12-27 15:11 UTC, parneet-guraya commented
Done

2025-02-01 02:30 UTC, sivaraam commented
Closing as #6167 got merged.

2025-02-01 02:30 UTC, closed without merging