FIXES :- Improve review feature documentation #3361
commons-app/apps-android-commons pull request #4915
Opened 2022-03-21 14:48 UTC by Rishavgupta12345

added the required detailed information in the review section under #3361 

This pull request is created to verify the changes and discuss them with the mentors , and then finalise the commit

2022-03-22 03:37 UTC, 4D17Y4 commented
This is certainly a good idea, but i would prefer info icons near questions.

2022-03-23 04:58 UTC, Rishavgupta12345 commented
@nicolas-raoul

2022-03-25 12:09 UTC, nicolas-raoul requested changes

2022-03-25 12:09 UTC, nicolas-raoul commented on app/src/main/res/values/strings.xml
> +  <string name="review_image_explanation">You can review images and improve the quality of Wikimedia Commons.\n The four parameters of review are: \n\n - Is this image in-scope? \n     when you say n
Could you please replace with this?
```
You can review images to improve the quality of Wikimedia Commons.\nThe four parameters of review are:\n\n- Is this image in-scope?\nWhen you tap "No" (out of scope), you are adding a deletion nomination template to this image.\n\n- Does this image follow the rules of copyright?\nWhen you tap "No" (does not follow the rules of copyright), you are adding a deletion nomination template to this image.\n\n- Is this image correctly categorized?\nWhen you tap "No" (not correctly categorized), you are adding a categorization request template to this image.\n\nIf everything is fine, no template is added to the image, and you get the opportunity thank the contributor.
```
Thanks!

2022-03-25 12:49 UTC, Rishavgupta12345 reviewed
done the requested changes @nicolas-raoul

2022-03-25 13:17 UTC, nicolas-raoul commented on app/src/main/res/values/strings.xml
> +  <string name="review_image_explanation">You can review images to improve the quality of Wikimedia Commons.\nThe four parameters of review are:\n\n- Is this image in-scope?\nWhen you tap "No" (out o
Also, I just realized that quotes do not show up and break the XML, so could you please replace all of the `"No"` with `No`? Thanks!

2022-03-25 13:59 UTC, Rishavgupta12345 reviewed
done @nicolas-raoul

2022-03-25 13:59 UTC, Rishavgupta12345 commented on app/src/main/res/values/strings.xml
> +  <string name="review_image_explanation">You can review images to improve the quality of Wikimedia Commons.\nThe four parameters of review are:\n\n- Is this image in-scope?\nWhen you tap "No" (out o
done

2022-03-26 00:21 UTC, nicolas-raoul commented
Thanks!

2022-03-26 00:21 UTC, nicolas-raoul approved these changes

2022-03-26 00:21 UTC, merged