Need to apply hidden categories
commons-app/apps-android-commons pull request #4924
Opened 2022-03-27 15:32 UTC by devarsh-mavani-19

**Description (required)**
hidden categories should be shown when searched for example  `[[Category:United Kingdom photographs taken on 2021-01-19]]`
Fixes #4192

What changes did you make and why?

added API call that will fetch hidden category when entered by user.
Tested {build variant, e.g. ProdDebug} on {name of device or emulator} with API level {API level}.
tested on prodDebug
device: Redmi 6 pro
API 28
android 9 (pie)

2022-03-27 15:33 UTC, devarsh-mavani-19 commented
will add tests and proper javadoc as soon as I can.

2022-03-27 18:42 UTC, devarsh-mavani-19 commented
@nicolas-raoul can you please review this? thanks

2022-03-27 18:52 UTC, 4D17Y4 commented
When a PR is still under work, u can change the title to [WIP]<pr name> or make it a draft.

2022-03-28 10:59 UTC, nicolas-raoul requested changes

2022-03-28 10:59 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/category/CategoriesModel.kt
> +    fun checkIfCategoryExists(query: String): Single<List<CategoryItem>> {
Could you please rename to `checkWhetherCategoryExists`?
The name `checkIfCategoryExists` might be misunderstood as "_if category exists, then check_".

2022-03-28 10:59 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/upload/categories/CategoriesPresenter.kt
> +    private fun checkCategoryExist(term: String) =
How about `checkWhetherCategoryExists`?

2022-03-28 14:08 UTC, nicolas-raoul commented
With this PR, categories that would normally be suggested (suggestions that come from depictions for instance) appear only for a fraction of a second, before disappearing.

2022-03-28 14:19 UTC, nicolas-raoul commented
1. Start uploading an image
2. At the depictions step, select depiction [Trégastel](https://www.wikidata.org/wiki/Q210421)
3. Go to the categories selection step
4. Problem: Normally the linked category should be suggested, but instead no categories are shown, the activity is blank
5. Type any letter, for instance "a", and the suggestions appear for a fraction of a second before disappearing.

2022-03-29 11:04 UTC, nicolas-raoul commented
This seems to work with most depictions I tried.

At step 5, a better workaround is to just drag to the bottom (like if scrolling). That makes the suggestions appear and stay. I will now try to reproduce on master, to see whether it is really caused by this pull request or not.

2022-03-29 12:38 UTC, nicolas-raoul commented
The problem seems to not exist on master.

2022-03-29 17:19 UTC, devarsh-mavani-19 commented
> 

hey, @nicolas-raoul I have fixed the issue. sorry for the delay.

2022-03-30 01:21 UTC, nicolas-raoul commented
> means is it caused by this PR?

It seems to be the case indeed.
Are you able to reproduce the issue using [the steps above](https://github.com/commons-app/apps-android-commons/pull/4924#issuecomment-1080715139)?

2022-03-30 01:41 UTC, nicolas-raoul commented
Sorry I had not seen your last comments, thank you for fixing!

2022-03-30 01:52 UTC, nicolas-raoul requested changes
Strangely I can't find https://commons.wikimedia.org/wiki/Category:United_Kingdom_photographs_taken_on_2021-01-19 by typing `United Kingdom photographs taken on 2021-01-19`. Am I missing something?
![adb](https://user-images.githubusercontent.com/99590/160734806-0fb01081-ce7c-410b-9b37-efec13857eae.png)

2022-03-30 03:48 UTC, devarsh-mavani-19 commented
> Strangely I can't find https://commons.wikimedia.org/wiki/Category:United_Kingdom_photographs_taken_on_2021-01-19 by typing `United Kingdom photographs taken on 2021-01-19`. Am I missing something? ![adb](https://user-images.githubusercontent.com/99590/160734806-0fb01081-ce7c-410b-9b37-efec13857eae.png)

That's strange I tried and it worked for me
![Screenshot_2022-03-30-09-15-51-111_fr free nrw commons](https://user-images.githubusercontent.com/55136047/160747595-6a7dc392-9844-4895-9852-079215986f4e.jpg)

2022-03-31 04:54 UTC, devarsh-mavani-19 commented
@nicolas-raoul I tried to reproduce error on different device as well but it is not showing that error in my case

2022-04-01 14:51 UTC, nicolas-raoul commented
Here is what logcat shows when I paste `United Kingdom photographs taken on 2021-01-19` in the categories search box:
```
04-01 23:47:57.629  5636  5803 I clp-JNI : Add pinfo.  (channel) 6a86011 PopupWindow:edae80d (server) (pkg) AppWindowToken{8d03d8c token=Token{14b72bf ActivityRecord{f9840de u0 fr.free.nrw.commons/.upload.UploadActivity t35203}}} 14585 10408 (action) 0
04-01 23:47:57.631 14585 14585 D ViewRootImpl@88cc510[PopupWindow:edae80d]: ViewPostIme pointer 0
04-01 23:47:57.685  5636  5803 I clp-JNI : Add pinfo.  (channel) 6a86011 PopupWindow:edae80d (server) (pkg) AppWindowToken{8d03d8c token=Token{14b72bf ActivityRecord{f9840de u0 fr.free.nrw.commons/.upload.UploadActivity t35203}}} 14585 10408 (action) 1
04-01 23:47:57.685 14585 14585 D ViewRootImpl@88cc510[PopupWindow:edae80d]: ViewPostIme pointer 1
04-01 23:47:57.689 14585 14585 D TextView: paste - clipdata type : HTML
04-01 23:47:57.700 14585 14585 D ViewRootImpl@88cc510[PopupWindow:edae80d]: dispatchDetachedFromWindow
04-01 23:47:57.704 14585 14585 D ViewRootImpl@88cc510[PopupWindow:edae80d]: Surface release. android.view.ViewRootImpl.doDie:7944 android.view.ViewRootImpl.die:7912 android.view.WindowManagerGlobal.removeViewLocked:497 android.view.WindowManagerGlobal.removeView:435 android.view.WindowManagerImpl.removeViewImmediate:124 android.widget.PopupWindow.dismissImmediate:2242 android.widget.PopupWindow.dismiss:2185 com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$4.onAnimationEnd:584 
04-01 23:47:57.708 14585 14585 D InputTransport: Input channel destroyed: fd=146
04-01 23:47:58.205 14585 15198 D OkHttp  : --> GET https://commons.wikimedia.org/w/api.php?action=query&format=json&formatversion=2&generator=allcategories&prop=categoryinfo|description|pageimages&piprop=thumbnail&pithumbsize=70&gacprefix=United%20Kingdom%20photographs%20taken%20on%202021-01-19&gaclimit=25&gacoffset=0
04-01 23:47:58.206 14585 15198 D CookieManager: Domain:commons.wikimedia.org
04-01 23:47:58.660 14585 15198 D OkHttp  : <-- 200 https://commons.wikimedia.org/w/api.php?action=query&format=json&formatversion=2&generator=allcategories&prop=categoryinfo|description|pageimages&piprop=thumbnail&pithumbsize=70&gacprefix=United%20Kingdom%20photographs%20taken%20on%202021-01-19&gaclimit=25&gacoffset=0 (455ms, 278-byte body)
```
then `No Categories found` appears.

2022-04-25 18:30 UTC, neslihanturan commented
hi @devarsh-mavani-19 , thanks for the PR. Is this PR still active?

2023-09-29 06:31 UTC, nicolas-raoul commented
Sorry for the delay @devarsh-mavani-19 would you mind rebasing (or pulling) from the latest main branch? Thanks!

2024-01-28 08:38 UTC, sivaraam commented
Closing due to dormancy of the MR. Feel free to reopen if you're willing to work on this. 🙂

2024-01-28 08:38 UTC, closed without merging