Fixes 4620 : Editing categories of an existing picture: Reuse categories selection UI from the Upload Wizard
commons-app/apps-android-commons pull request #4928
Opened 2022-04-10 06:22 UTC by Ayan-10

**Description (required)**

Fixes #4620

**What changes did you make and why?**

App currently uses a special UI, which takes time to improve and maintain. It would be better if it reused the existing category selection UI of the Upload Wizard.

- Reuse categories selection UI from the Upload Wizard
- Deleted old UI
- Added tests for new lines

**Tests performed (required)**

Tested latest prodDebug on Pixel 3 with API level 30.

**Screenshots (for UI changes only)**

**New UI**

<img src="https://user-images.githubusercontent.com/71203077/162604730-4efc5cba-202d-4d82-a6f1-b700eb3e2aff.png" width=300/>

**Old UI**

<img src="https://user-images.githubusercontent.com/71203077/162605242-ff6ec298-f57a-4d07-8a0d-e2dbd91d0b61.png" width=300/>

2022-04-10 12:12 UTC, Ayan-10 commented
@nicolas-raoul For now, I removed `values-zh-hk` directory so that the PR can be tested and reviewed. After approval of the PR, I can add the directory if required.

Thanks.

2022-04-11 09:34 UTC, nicolas-raoul requested changes
It works great, and the code looks fine to me.
Just two minor change requests.

2022-04-11 09:34 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/category/CategoryEditHelper.java
> +import io.reactivex.schedulers.Schedulers;
This line is not needed, right?

2022-04-11 09:34 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/upload/categories/CategoriesPresenter.kt
> +                                "Failed to update depictions"
Do you mean `categories`?

2022-04-11 10:19 UTC, Ayan-10 commented on app/src/main/java/fr/free/nrw/commons/upload/categories/CategoriesPresenter.kt
> +                                "Failed to update depictions"
Yes.

2022-04-11 10:30 UTC, nicolas-raoul approved these changes

2022-04-11 10:30 UTC, merged