Add prompt before asking for location in Nearby and Explore Maps
commons-app/apps-android-commons pull request #5034
Opened 2022-08-15 11:18 UTC by madhurgupta10

**Description**
Fixes #5031 

**Tests performed**
Tested betaDebug on Google Pixel 5 with API level 31

2022-08-15 22:16 UTC, nicolas-raoul requested changes

2022-08-15 22:16 UTC, nicolas-raoul commented on app/src/main/res/values/strings.xml
> +    display nearby places that need photos even when the app is in background.</string>
I would say "in the background".
I unfortunately can't test right now, but apart from this it looks fine so feel free to merge. 🙂

2022-08-15 22:18 UTC, nicolas-raoul commented on app/src/main/res/values/strings.xml
> +    display nearby places that need photos even when the app is in background.</string>
and maybe "photos," instead of "photos"? Comma removes an ambiguity and makes the sentence easier to read, I think.

2022-08-16 09:20 UTC, misaochan approved these changes
LGTM. Fixed the string, merging. Thanks Madhur!

2022-08-16 09:21 UTC, merged