Fix #4985：Can not type Japanese space in the caption field
commons-app/apps-android-commons pull request #5071
Opened 2022-10-16 01:49 UTC by zhihaoyuu

Added jpSpace2EnSapce method to call in the filter

Fix #4985：Can not type Japanese space in the caption field

Japanese spaces cannot be input successfully in the input box but in order to ensure the integrity of the input as much as possible. According to the prompts in the link, in UploadMediaDetailInputFilter.java, add a new filter to input content, and convert it into English spaces when querying Japanese spaces.

file location：/app/src/main/java/fr/free/nrw/commons/upload/UploadMediaDetailInputFilter.java

**Description (required)**

Fixes #INSERT_ISSUE_NUMBER_HERE

What changes did you make and why?

**Tests performed (required)**

Tested {build variant, e.g. ProdDebug} on {name of device or emulator} with API level {API level}.

**Screenshots (for UI changes only)**

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

2022-10-16 11:07 UTC, nicolas-raoul reviewed
So, with this pull request, what happens when I type a Japanese space? Does a space correctly appear in the input field? Thanks!

2022-10-16 14:05 UTC, zhihaoyuu commented
hi, When you enter a Japanese space, the display is an English space

2022-10-16 14:05 UTC, zhihaoyuu commented
> So, with this pull request, what happens when I type a Japanese space? Does a space correctly appear in the input field? Thanks!

hi，When you enter a Japanese space, the display is an English space

2023-01-30 13:54 UTC, nicolas-raoul requested changes

2023-01-30 13:54 UTC, nicolas-raoul commented on UploadMediaDetailInputFilter.java
> +    private CharSequence jpSpace2EnSapce(CharSequence jpSpace) {
Would you mind renaming the method to `japaneseSpaceToEnglishSpace`?
And jpSpace to just `text`.

2023-01-30 13:54 UTC, nicolas-raoul commented on UploadMediaDetailInputFilter.java
> +            Pattern.compile("[\\x{00A0}\\x{1680}\\x{180E}\\x{2000}-\\x{200B}\\x{2028}\\x{2029}\\x{202F}\\x{205F}\\x{3000}]"),
Would you mind adding at the end of each line the comment found at https://commons.wikimedia.org/wiki/MediaWiki:Titleblacklist, for instance `// NBSP and other unusual spaces`? Thanks!

2023-09-29 07:24 UTC, closed without merging