Add option to centre on GPS location for issue #5008
commons-app/apps-android-commons pull request #5098
Opened 2022-10-26 04:58 UTC by russianbear222

**Description (required)**

Add option to center on GPS location from issue #5008 

In layout, add floatactionbutton and add new method addCentreOnGPSButton() in LocationPickerActivity. Users can click the button to be redirected to the device's current location.

**Tests performed (required)**

Tested {LocationPickerActivity} on {Pixel 2} with API level {API level 30}.
No change to LocationPickerActivityUnitTests due to a lack of understanding of the test file format. When performing the test, a NullException error occurred.

**Screenshots (for UI changes only)**
![Screenshot 2022-10-26 155455](https://user-images.githubusercontent.com/45113399/197938509-0690a5be-ae10-4499-8980-3a9c4fa32f9b.png)

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

2022-10-26 05:17 UTC, russianbear222 commented on app/src/main/java/fr/free/nrw/commons/LocationPicker/LocationPickerActivity.java
> +     * cGPS : textView of centre to location
This should be 
/**
     * largeToolbarText : textView of shadow
     */
I forgot to change it back.

2022-10-29 09:42 UTC, nicolas-raoul requested changes
Looks good, just a few details.

2022-10-29 09:42 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/LocationPicker/LocationPickerActivity.java
Please add a comment explaining what feature this section is for.

2022-10-29 09:42 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/LocationPicker/LocationPickerActivity.java
> +    FloatingActionButton cGPS;
Would you mind renaming the variable to `fabCenterOnLocation`? Unlike C++/etc, in Java the most common convention is to use long explicit names. Thanks!

2022-10-29 09:44 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/LocationPicker/LocationPickerActivity.java
> +     * Centre the camera on the last saved location
In the rest of the project we use US spelling, would you mind changing this and other occurrences to "center"? Thanks!

2022-10-29 12:16 UTC, russianbear222 commented
Following your comments, I have fixed the issue and created a new pull request.

2022-10-29 12:19 UTC, russianbear222 commented
Sorry @nicolas-raoul  I accidentally closed it, I have committed and fixed all the things mentioned by you.

2022-10-30 07:44 UTC, nicolas-raoul requested changes
Getting better :-)

2022-10-30 07:44 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/LocationPicker/LocationPickerActivity.java
> +     * Centre the camera on the last saved location
Would you mind fixing the "Centre" word in the javadoc comment above? Also in centre_on_gps and getCentre.

2022-10-30 07:44 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/LocationPicker/LocationPickerActivity.java
> +    void getCentre() {
please separate methods with an empty line, and add javadoc for getCenter

2022-10-30 09:53 UTC, russianbear222 commented
@nicolas-raoul I fixed it.

2022-10-30 10:01 UTC, nicolas-raoul requested changes

2022-10-30 10:01 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/LocationPicker/LocationPickerActivity.java
> +        fabCenterOnLocation = findViewById(R.id.centre_on_gps);
-> center_on_gps

2022-10-30 10:01 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/LocationPicker/LocationPickerActivity.java
> +        fabCenterOnLocation.setOnClickListener(view -> getCentre());
-> getCenter

2022-10-30 10:28 UTC, russianbear222 commented
@nicolas-raoul I fixed it.

2022-10-30 10:32 UTC, russianbear222 commented
@nicolas-raoul Okay I think that is all the center.

2022-12-17 14:04 UTC, nicolas-raoul approved these changes
Code looks good.
Tested, works great.
Sorry for the time it took! Merging bug fixes is usually much faster than merging enhancements. :-)

2022-12-17 14:05 UTC, merged