3463 replace assert with assert that
commons-app/apps-android-commons pull request #5107
Opened 2022-10-30 10:07 UTC by u7281898

**Description (required)**

Fixes #3463

What changes did you make and why?

I replaced all instances of assert() with assertThat() where appropriate. 
assertThat() error messages are easier to understand and the assertThat method has a wider range of abilities to determine if the output of a function is appropriate. For example assertThat will not complete compiling instead of failing if the expected input is an integer instead of a string.

**Tests performed (required)**

Tested AccountUtilUnitTest with Pixel 2 API 30

2022-10-31 09:44 UTC, nicolas-raoul requested changes
Looks good generally, just a few minor things to improve.

2022-10-31 09:44 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java
> +//            assertThat(data, not(nullValue()));
Is this really needed?

2022-10-31 09:44 UTC, nicolas-raoul commented on data-client/build.gradle
> +        targetSdkVersion 30
Is this really needed?

2022-10-31 09:44 UTC, nicolas-raoul commented on app/src/test/kotlin/fr/free/nrw/commons/auth/AccountUtilUnitTest.kt
> +import org.junit.Assert.*
Would you mind importing only the needed classes, explicitly?

2022-10-31 09:44 UTC, nicolas-raoul commented on app/src/test/kotlin/fr/free/nrw/commons/auth/AccountUtilUnitTest.kt
> +import org.hamcrest.CoreMatchers.*;
Would you mind importing only the needed classes, explicitly?

2024-02-18 15:06 UTC, domdomegg commented
Closing this as now stale

2024-02-18 15:06 UTC, closed without merging