Fix #5151: Use DialogUtil for MediaDetailFragment
commons-app/apps-android-commons pull request #5153
Opened 2023-02-21 21:18 UTC by chan-j-d

**Description (required)**

Fixes #5151

What changes did you make and why?

DialogUtil methods show and return the dialog object as well to be used more flexibly. Additionally, this PR also has an overlapping change with #5152 with the DialogUtil accepting nulls in order to prevent abnormally large empty boxes when a title or message is set to an empty string. 

For the changes in MediaDetailFragment, there might be changes to the logical flow of the code but I tried to keep it as similar as possible. The main difference is that for the second case, it calls show before setting the `input` properly. But from my testing, it seems both cases still function identical to the master branch. 

I'm not entirely sure if this change is necessary as it might be better to leave the more specific Builder uses as is. 

**Tests performed (required)**

Tested betaDebug on Pixel XL with API level 30.

**Screenshots (for UI changes only)**

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

2023-02-24 09:07 UTC, nicolas-raoul requested changes
It looks like a positive change to me.
Would you mind solving the conflict? :-)

2023-02-24 10:28 UTC, chan-j-d commented on app/src/main/java/fr/free/nrw/commons/utils/DialogUtil.kt
> +            message?.also{setMessage(message)}
Unfortunately, I think I wrongly edited this in the previous PR and this should fix it. The previous would result in an empty title not setting a message even if it was provided

2023-02-24 10:30 UTC, chan-j-d commented
Resolved!

2023-02-25 06:34 UTC, nicolas-raoul approved these changes

2023-02-25 06:34 UTC, merged