#5030 Bug fix  "Author field shows HTML tags when template used"
commons-app/apps-android-commons pull request #5186
Opened 2023-03-23 10:20 UTC by shankarpriyank

Added a new function getDisplayAuthor in Media.kt that parses the author string with Regex, also added some tests for it

**Description (required)**
Fixes #5030

Just added a few tests to the changes made in #5069

2023-03-24 07:02 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/Media.kt
> +
Remove extra line between documentation and function

2023-03-24 07:05 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/Media.kt
> +        if(completeCheckResult.count()==1) return completeCheckResult.toList().get(0).groupValues.get(1) // Get matching result and return text between tag - text between tag is inside a capture grou
Please use these spacing conventions: https://kotlinlang.org/docs/coding-conventions.html#horizontal-whitespace

Also, better split this into 3 lines:
```
// comment
if ...
    return ...

```
with a new line before and after.

2023-03-24 07:06 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/Media.kt
> +        if(hrefTagCheckResult.count()==1) return hrefTagCheckResult.toList().get(0).groupValues.get(1) // Get matching result and return text between tag
new line before, spacing, split each of these two lines into two.

2023-03-24 07:06 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/Media.kt
> +
no need for a new line here.

2023-03-24 07:07 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/Media.kt
> +
Only one new line is enough.

2023-03-24 07:13 UTC, nicolas-raoul requested changes
A few stylistic changes requested.
Thanks for the unit tests!
I will now test this change for a while with real-world users.

2023-03-24 08:52 UTC, shankarpriyank commented
@nicolas-raoul I have made the changes as requested, also please approve the ci check, there were 2 failing tests earlier I have fixed them.

2023-03-24 09:52 UTC, nicolas-raoul requested changes
Thanks! Just a few spacing issues left.

2023-03-24 09:52 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/Media.kt
> +        if(completeCheckResult.count()==1)
Spaces before and after `==` here and below.

2023-03-24 09:52 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/Media.kt
> +        else if (completeCheckResult.count()>1)
Spaces before and after `>`.

2023-03-24 09:52 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/Media.kt
> +        if(completeCheckResult.count()==1)
Space after `if` here and below.

2023-03-24 09:53 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/Media.kt
> +    fun getDisplayAuthor(): String{
Space before `{`.

2023-03-24 10:15 UTC, shankarpriyank commented
@nicolas-raoul Sorry for the iteration, I have made the changes as requested.
I also have a suggestion, maybe we can a linter to the project and use a pre commit hook to run a basic linting command and a linting check. Then most of the styling issues will be automatically fixed.

2023-03-24 13:56 UTC, nicolas-raoul reviewed
Looks great now!

Would you mind checking whether anything can be done for cases such as the one I described at https://github.com/commons-app/apps-android-commons/issues/5030#issuecomment-1482386712? Why does the output becomes empty? If this looks like a different problem, feel free to create a separate issue. Thanks a lot!

2023-03-24 19:16 UTC, shankarpriyank commented
That seems like a different issue to be right now, but I think we can investigate a lil more before jumping to conclusions([I have asked for some info in the issue](https://github.com/commons-app/apps-android-commons/issues/5030#issuecomment-1483291921)).

Also the pr still shows _changes requested._

2023-03-25 06:40 UTC, nicolas-raoul commented
The pull request still shows changes requested even though I marked all issues as resolved, you can disregard this status.

In the case of https://commons.wikimedia.org/wiki/File:Mastl%C3%A9_Odles_Stevia.jpg what is the string that `getDisplayAuthor()` receives as input? Please paste the whole input string here, thanks!

2023-03-25 07:13 UTC, shankarpriyank commented
@nicolas-raoul 
`<tbody><tr class="plainlinks"><td><a href="//commons.wikimedia.org/wiki/File:Emblem-camera.svg" class="image"><img alt="Emblem-camera.svg" src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Emblem-camera.svg/25px-Emblem-camera.svg.png" decoding="async" width="25" height="25" srcset="https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Emblem-camera.svg/38px-Emblem-camera.svg.png 1.5x, https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Emblem-camera.svg/50px-Emblem-camera.svg.png 2x" data-file-width="64" data-file-height="64">`

This is what we get as the author(the input in getDisplayAuthor). As Ritika said, this indeed is the icon of a camera. No useful information is present in the author field

2023-03-25 08:01 UTC, nicolas-raoul commented
Strange, it seems to be cut. The full HTML should be much larger, containing all of the other parts of the template such as the email image and the "Wolfgang Moroder" text.

Would you mind checking whether our app is cutting this HTML, or whether the API gives us only this truncated version? If the latter, we need to find a way to get the whole HTML, as not showing the author name might be a copyright license violation.

2023-04-03 07:06 UTC, nicolas-raoul requested changes
Sorry, we should first get the author name from Structured Data, as discussed recently at https://github.com/commons-app/apps-android-commons/issues/5030#issuecomment-1483789016. Thank you for the several great improvements to this pull request!

2023-04-03 10:53 UTC, shankarpriyank commented
I will have a look, although this may take some time though as this seems a bit new to me

2024-02-18 15:06 UTC, domdomegg commented
Closing this as now stale

2024-02-18 15:06 UTC, closed without merging