Enable support toolbar for ProfileActivity and added a couple of unit…
commons-app/apps-android-commons pull request #5188
Opened 2023-03-24 12:34 UTC by shankarpriyank

**Description (required)**

Fixes #5026

What changes did you make and why?
Added a couple of unit tests to #5068

2023-03-24 14:04 UTC, nicolas-raoul commented
And would you mind posting before/after screenshots? Thanks!

2023-03-25 09:04 UTC, shankarpriyank commented
@nicolas-raoul Added the screenshots and made a very minor change in the MediaDetailPagerFragment.java.
Can you please point out some coding style violations (everything seems fine to me now)?

2023-03-25 10:25 UTC, nicolas-raoul requested changes

2023-03-25 10:25 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java
> +        if(getActivity() instanceof ProfileActivity){ return;}
Space after if

2023-03-25 10:25 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java
> +            mediaDetailPagerFragment = new MediaDetailPagerFragment(false,true);
Space after ,

2023-03-25 10:25 UTC, nicolas-raoul commented on app/src/test/kotlin/fr/free/nrw/commons/media/MediaDetailPagerFragmentUnitTests.kt
> +        fragment = MediaDetailPagerFragment(false,true)
idem

2023-03-25 21:00 UTC, shankarpriyank commented
@nicolas-raoul Thanks for pointing out the errors. I have made the changes as requested.

2023-03-27 06:13 UTC, nicolas-raoul requested changes

2023-03-27 06:13 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java
> +        if (getActivity() instanceof ProfileActivity) { return;}
Space before `}`

2023-03-27 06:13 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/profile/ProfileActivity.java
> -        if (shouldShowContributions) {
In the past, why was this `if (shouldShowContributions) {` added? You can use `git blame` to find out.

2023-03-27 11:19 UTC, shankarpriyank commented
@nicolas-raoul Made the requested changes and ` if (shouldShowContributions)` was added in this pr https://github.com/commons-app/apps-android-commons/pull/4678

2023-04-03 07:02 UTC, nicolas-raoul approved these changes
Working well, thank you!

2023-04-03 07:02 UTC, merged

2023-04-03 14:32 UTC, shankarpriyank commented
Hey @nicolas-raoul I was having a look at the issues trying to decide what to pick next. I am a bit confused right now. If you have any issues in mind, that might be suitable for me please let me know