Makes depicted place and category items unselectable for nearby place
commons-app/apps-android-commons pull request #5325
Opened 2023-10-03 12:51 UTC by srishti-R

**Description (required)**

Fixes #5317 

What changes did you make and why?
Makes the place and category unselectable

**Tests performed (required)**

Tested {prodDebug} on {pixel 5 emulator} with API level {34, 30}.

**Screenshots (for UI changes only)**
![greyed_check](https://github.com/commons-app/apps-android-commons/assets/53987325/77c99a93-13c4-4f89-897d-ff70cabf8c00)

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

2023-10-03 13:58 UTC, nicolas-raoul requested changes
I just tested with a Wikidata item that has no associated category, it seems like a strange "Hidden" category is shown instead of nothing being pre-selected:

https://github.com/commons-app/apps-android-commons/assets/99590/927896ca-d8f8-4ab5-804b-01e71486b407

2023-10-03 13:58 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/repository/UploadRepository.java
> +    public Single<List<CategoryItem>> getCategoryDepictions() {
How about renaming this to `getPlaceCategories`, would it make sense?

2023-10-03 13:58 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/upload/categories/CategoriesPresenter.kt
> +
Would you mind adding Javadoc here?

2023-10-03 15:37 UTC, srishti-R commented
> I just tested with a Wikidata item that has no associated category (https://www.wikidata.org/wiki/Q105799610 embassy of Brazil in Costa Rica), it seems like a strange "Hidden" category is shown instead of nothing being pre-selected:
> 
> It seems to work great with Fukusho-ji (which has an associated category).

I thought this was intended, will remove.

2023-10-04 07:32 UTC, srishti-R commented
@nicolas-raoul made the requested changes, "hidden" is no longer a category that appears checked when no category is there. Need some help with 2 failing tests inside CategoriesPresenterTests.kt, I have never written tests for RxJava before and I have used up every brain cell available to fix those two.

2023-10-04 13:55 UTC, nicolas-raoul commented
Note: Just tested, it works great now, thanks! I did not actually upload any file but I will try to, probably in the next few days.

About the unit tests: Would you mind creating a new issue about it? Please include Git repo/branch info to make it easily reproducible. Thanks! :-)

2023-10-08 08:58 UTC, srishti-R commented
@nicolas-raoul I was able to fix all the CategoriesPresenter failing tests as here #5327. One confirmation I needed to make this deselectable feature better. Suppose we upload a set of images that have exif attached, we confirm by saying "Yes" to "is this a photo of some place nearby?", after this, shouldn't the depiction and category also be unselectable? Currently its not. We can choose to select/unselect the depiction and category in this specific case.

2023-10-08 09:25 UTC, nicolas-raoul approved these changes
Tested again, it still works great (I did not actually finish the upload though as I did not have suitable pictures)

2023-10-08 09:26 UTC, merged

2023-10-08 09:38 UTC, nicolas-raoul commented
When using Nearby, the app does assign the uploaded picture to the Wikidata item. Even if the user changes their mind they have no way to prevent this assignment from taking place. So if they change their mind, they MUST just cancel their upload.

On the other side, even after selecting "Yes" for "is this a photo of some place nearby?", the user can still modify everything (captions/descriptions/depictions/categories), and it will be like if they has selected "No". The Wikidata item is not modified.

Summary: Nearby upload MUST be about that Wikidata item. Normal upload does not have such restrictions.