Remove exif data
commons-app/apps-android-commons pull request #5348
Opened 2023-10-18 13:16 UTC by shankarpriyank

Fixed removal of exif data, I could not find paco's repository in the list of main repository hence I selected the main to be the base branch.

2023-10-18 13:38 UTC, nicolas-raoul requested changes

2023-10-18 13:38 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java
> +
Would you mind removing the extra blank lines here?

2023-10-18 13:38 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java
> +
and here

2023-10-18 13:38 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/upload/mediaDetails/UploadMediaDetailFragment.java
> +            Toast.makeText(getContext(), "Location Could Not be Removed", Toast.LENGTH_LONG).show();
indentation seems a bit off?

2023-10-18 13:43 UTC, shankarpriyank commented
Fixed
I think adding a linter would help save a lot of time I could use some help with #5198

2023-10-18 14:52 UTC, shankarpriyank commented
i forgot adding a line to save the changes, should work as intended now.
in case it doesn't, please send me a couple of pictures with exif location

2023-10-18 23:14 UTC, nicolas-raoul requested changes
It is working great now!
https://commons.m.wikimedia.org/wiki/File%3ATOKUYAMA-brand_%E5%A1%A9%E5%8C%96%E3%82%AB%E3%83%AB%E3%82%B7%E3%82%A6%E3%83%A0_on_bridge_to_Koneshima.jpg

Would you mind fixing these 2 unit tests?

2023-10-18T14:50:39.7865366Z 
2023-10-18T14:50:39.7867579Z fr.free.nrw.commons.locationpicker.LocationPickerActivityUnitTests > testOnClickModifyLocation FAILED
2023-10-18T14:50:39.7870023Z     java.lang.reflect.InvocationTargetException at LocationPickerActivityUnitTests.kt:220
2023-10-18T14:50:39.7871412Z         Caused by: java.lang.NullPointerException at LocationPickerActivityUnitTests.kt:220
2023-10-18T14:50:40.2892517Z 
2023-10-18T14:50:40.2894112Z fr.free.nrw.commons.locationpicker.LocationPickerActivityUnitTests > testOnStyleLoaded FAILED
2023-10-18T14:50:40.2895823Z     java.lang.reflect.InvocationTargetException at LocationPickerActivityUnitTests.kt:204

2023-11-04 19:00 UTC, shankarpriyank commented
I am having a hard time fixing the tests
`java.lang.instrument.IllegalClassFormatException: Error while instrumenting fr/free/nrw/commons/LocationPicker/LocationPickerActivity with JaCoCo 0.8.10.202304240956/8ea9668.
`
This the error in both of them, any idea how to fix them?

2023-11-04 21:34 UTC, nicolas-raoul commented
Feel free to create a new issue about it asking for help, referring to your branch.

2024-03-03 16:35 UTC, rohit9625 commented
@shankarpriyank 
Did you create any other issue for the unit tests that required merging this PR?

2024-03-30 15:07 UTC, closed without merging