Replaced campaignPreference with CAMPAIGNS_DEFAULT_PREFERENCE
commons-app/apps-android-commons pull request #5357
Opened 2023-10-21 03:42 UTC by Kwong-Yu-Zhou

Fixed the bug "Swiping campaign notification shows 'You won't see campaigns anymore', but actually same notification comes back after a few days."

Fixes #5288

What changes did you make and why?

I replaced the variable _campaignPreference_ with _CAMPAIGNS_DEFAULT_PREFERENCE_. 

In the _**ContributionsFragment**_ class, the function _fetchCampaigns_() checks the _CAMPAIGNS_DEFAULT_PREFERENCE_ if it is True. However, in the **_CampaignView_** class, it switches  _campaignPreference_ to False without updating the default preference after swiping.

https://github.com/commons-app/apps-android-commons/blob/1490710a514e58ea5052868637da60dd3ccec1b3/app/src/main/java/fr/free/nrw/commons/contributions/ContributionsFragment.java#L591

https://github.com/commons-app/apps-android-commons/blob/1490710a514e58ea5052868637da60dd3ccec1b3/app/src/main/java/fr/free/nrw/commons/campaigns/CampaignView.java#L72

Tested {} on {emulator 32.1.12-9751036} with API level {API Tiramisu}.

**Screenshots (for UI changes only)**

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

2023-10-25 04:50 UTC, nicolas-raoul commented
I added a currently-running campaign so that it can be tested.
Strangely now I can nor reproduce the issue on the main branch... are you able to reproduce it? if yes, any tip to make it happen reliably? Thanks! :-)

2024-02-14 21:09 UTC, domdomegg requested changes

2024-02-14 21:09 UTC, domdomegg commented on app/src/main/java/fr/free/nrw/commons/campaigns/CampaignView.java
> +            .putBoolean(CAMPAIGNS_DEFAULT_PREFERENCE, false); // Issue 5288: Replaced campaignPreference with CAMPAIGNS_DEFAULT_PREFERENCE
```suggestion
            .putBoolean(CAMPAIGNS_DEFAULT_PREFERENCE, false);
```

2024-02-14 21:09 UTC, domdomegg approved these changes

2024-02-14 21:23 UTC, merged