Keeping track of and restart interrupted uploads
commons-app/apps-android-commons pull request #5371
Opened 2023-10-29 11:36 UTC by Tup0lev

**Description (required)**
Add the ability to keep track of and reupload interrupted uploads

Fixes #5282

What changes did you make and why?
Added a Java class to record unfinished uploads on disk, to keep track of the uploads across app closure/device restarts. 
**Tests performed (required)**

Tested {Beta} on {Pixel 7 Pro} with API level {33}.

**Screenshots (for UI changes only)**

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

2023-10-30 00:30 UTC, nicolas-raoul requested changes

2023-10-30 00:30 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/CommonsApplication.java
> +                //TODO: restart the upload
This would be an important part I guess. 🙂

2023-10-30 00:30 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/CommonsApplication.java
> +    public static Map<String, Boolean> unfinishedUploads = new HashMap<>();
Better avoid public members, especially for modifyable data structures. Better make it private and add public methods to modify the data in intended ways.

2023-10-30 00:30 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/CommonsApplication.java
> +    private void notifyUser() {
Ideally retry would happen automatically, with no user action.

2024-02-09 03:32 UTC, sivaraam commented
@Tup0lev Thanks for your contribution. 🙂 


ust pinging to know if you could look into comments given by Nicolas

2024-02-09 03:43 UTC, closed without merging