Send thanks button in more details fragment
commons-app/apps-android-commons pull request #5424
Opened 2024-01-08 15:19 UTC by srishti-R

**Description (required)**

Fixes #5421 

What changes did you make and why?
Send thank button will appear only when the image is not uploaded by author.
![Screenshot_20240108-203814_Commons](https://github.com/commons-app/apps-android-commons/assets/53987325/10658e6c-9db7-4449-812b-58e975bedc00)
![Screenshot_20240108-203825_Commons](https://github.com/commons-app/apps-android-commons/assets/53987325/a017bad1-05e6-4af8-9ea9-da07a6ad8d97)
![Screenshot_20240108-203826_Commons](https://github.com/commons-app/apps-android-commons/assets/53987325/9cf3ccfa-88ce-4f05-a12a-cd9160b22200)
![Screenshot_20240108-203859_Commons](https://github.com/commons-app/apps-android-commons/assets/53987325/a695dceb-6fb1-482a-9be2-064a73c9a9b7)

**Tests performed (required)**

Tested prodDebug on Samsung galaxy M31 with API level 31.

**Screenshots (for UI changes only)**

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

2024-01-10 13:57 UTC, nicolas-raoul requested changes
Working great!
I checked all places I could think of where images are visible, then checked that the thanks were correctly sent (at https://commons.wikimedia.org/wiki/Special:Log?type=thanks&user=Syced&page=&wpdate=&tagfilter=&wpFormIdentifier=logeventslist)

2024-01-10 13:57 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java
> +        if (AccountUtil.getUserName(getContext()) != null && media != null && AccountUtil.getUserName(getContext()).equals(media.getAuthor())) {
How about splitting this very long line?

2024-01-10 13:57 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java
> +    @OnClick(R.id.sendThanks)
Would you mind writing some Javadoc for each added method?

2024-01-10 13:57 UTC, nicolas-raoul commented on app/src/main/res/values/strings.xml
> +  <string name="send_thanks_to_author">Send thanks to author</string>
How about a shorter "Thank the author"?

2024-01-14 12:51 UTC, nicolas-raoul commented
In order to fix the unit tests, would you mind rebasing (or pulling) from main? Thanks :-)

2024-01-23 03:55 UTC, srishti-R commented
@nicolas-raoul made the changes, sorry for the delay

2024-01-23 13:55 UTC, nicolas-raoul approved these changes
Sorry for the delay, it somehow escaped my attention.

It works great and the code looks good. Thanks a lot! :-)

2024-01-23 13:55 UTC, merged