Replaced mapbox to osmdroid (Upload Activity)
commons-app/apps-android-commons pull request #5443
Opened 2024-01-15 20:43 UTC by kanahia1

**Description (required)**

Fixes #5414 

**Tests performed (required)**

Tested betaDebug on Samsung S21 FE with API level 33.

**Screenshots (for UI changes only)**
https://github.com/commons-app/apps-android-commons/assets/114223204/69139492-02bf-4f35-8ff1-c0ec46871c85

2024-01-16 13:36 UTC, nicolas-raoul requested changes
It works great, except that in the Image Location activity (the activity that appears when you tap the Media Details' map icon) the pin should be fixed to the map. The pin should be movable to a different latitude/longitude only in the `Edit Location` activity.
I added a few other minor observations. :-)
Thanks!

2024-01-16 14:05 UTC, kanahia1 commented on app/src/main/res/drawable/ic_location_marker.xml
> +<?xml version="1.0" encoding="utf-8"?>
Sure I will reuse the same, Actually I was trying to recreate similar design present earlier in mapbox.

2024-01-16 18:28 UTC, kanahia1 commented
Hi @nicolas-raoul , I have made all the suggested changes ;-).  Should we change the color of marker in location picker similar to https://github.com/commons-app/apps-android-commons/pull/5440 ?

https://github.com/commons-app/apps-android-commons/assets/114223204/6a6449b7-12ce-494d-a459-a96fe817839f

2024-01-17 06:44 UTC, nicolas-raoul commented
Your screencast looks great!
It is true that the position marker is a bit hard to see in dark mode, would you mind changing it? Thanks a lot!

2024-01-17 09:16 UTC, nicolas-raoul approved these changes

2024-01-17 10:06 UTC, kanahia1 commented
Thank you ;) for feedback @nicolas-raoul , I have changed the color of selected location marker https://github.com/commons-app/apps-android-commons/pull/5443/commits/9814bfe51caf5f2ca1d392b2a2a39671c5c0dc29

![WhatsApp Image 2024-01-17 at 15 35 07_4b6e5e07](https://github.com/commons-app/apps-android-commons/assets/114223204/fa4c7ba7-4038-46ac-8d6c-0a80d98740e9)

2024-01-18 05:28 UTC, merged