Fix DNG/RAW Upload Error
commons-app/apps-android-commons pull request #5543
Opened 2024-02-12 14:21 UTC by shashankiitbhu

**Description (required)**

Fixes #5537 

What changes did you make and why?
Restrict users to only pick Images whose types are allowed by Wikimedia Commons (as mentioned here: https://commons.wikimedia.org/wiki/Commons:File_types)

**Tests performed (required)**

Tested 4.2.1-debug-main on Xiaomi 11 Lite NE with API level 33

**Screenshots (for UI changes only)**

2024-02-13 01:56 UTC, sivaraam requested changes
Thabks for working on this. I took a glance at the change. I suppose we still need to support more formats.

2024-02-13 01:56 UTC, sivaraam commented on app/src/main/java/fr/free/nrw/commons/customselector/ui/selector/ImageFileLoader.kt
> +                    if (extension.lowercase(Locale.ROOT) in arrayOf("jpg", "jpeg", "png", "svg")) {
Do we not need to consider other supported types such as GIF, TIFF etc.

Kindly check the page. It lists more formats that we could support?

2024-02-13 01:56 UTC, sivaraam commented on app/src/main/java/fr/free/nrw/commons/filepicker/FilePicker.java
> +        final String[] mimeTypes =  { "image/jpg","image/png","image/jpeg","image/svg"};
Ditto here about making list more exhaustive.

2024-02-13 06:41 UTC, shashankiitbhu commented
@sivaraam Made the changes according to the supported formats mentioned on the webpage, Please Review it

2024-02-14 09:43 UTC, nicolas-raoul requested changes

2024-02-14 09:43 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/customselector/ui/selector/ImageFileLoader.kt
> +                    if (extension.lowercase(Locale.ROOT) in arrayOf("jpg", "jpeg", "png", "svg", "gif", "tiff", "webp", "xcf")) {
Can you please do `if ( ! extension.lowercase(Locale.ROOT) in arrayOf(...`?

Process exceptional cases first, then go on with the normal flow.
This avoids too may levels of if else.
See https://www.refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html

2024-02-14 12:09 UTC, nicolas-raoul approved these changes
Correctly blocking RAW.
Can still successfully upload JPG.

2024-02-14 12:09 UTC, merged