Fixes #5571 - Removed values-yue-hant file.
commons-app/apps-android-commons pull request #5573
Opened 2024-02-25 19:36 UTC by amrhossamdev

**Description (required)**

Fixes #5571 

What changes did you make and why?

Removed values-yue-hant, the error happened because Android expects a specific format for resource directory names, and values-yue-hant does not conform to these expectations, also there is exist values-yue with the same translate

**Tests performed (required)**

I used `gradle :app:testBetaDebugUnitTest` Tested on Google pixel 6A with API level 31

2024-02-26 01:56 UTC, sivaraam commented
Thanks for the contribution.

Have you confirmed that `yue` is the actual language map for the `yue-hant` language code? If so, could you share the supporting resources for the same? We need to be sure we're not accidentally removing support for a language 🙂

2024-02-26 01:58 UTC, sivaraam commented
Also, there's the translatewiki part that needs to be take care of (in case `yue-hant` should indeed be mapped to `yue`). Would you be able to cover that too?

2024-02-26 09:43 UTC, nicolas-raoul requested changes
Need gerrit change first

2024-02-27 21:48 UTC, amrhossamdev commented
Yes, we can rename it, but values-yue-that will be mapped to values-yue, so removing the file will also work because they have the same translation.

2024-02-28 08:33 UTC, sivaraam commented
> Yes, we can rename it, but values-yue-that will be mapped to values-yue, 

You seem to presume we've already mapped values-yue-Hant to values-yue. Could you let me know where we've done it? Also, if we can keep it separate I'm not sure why we would want to even map it 🤔 

> so removing the file will also work because they have the same translation.

It may have the same translation now but that doesn't always need to be the case. I suppose you might need to explore their difference clearly to understand why mapping it may not be ideal.

2024-02-28 12:32 UTC, amrhossamdev commented
You are right, maybe we can try changing the name of the file to values-b+yue+Hant, instead of removing it. I assumed that it was a static string sorry for I'm sorry for that.

2024-02-28 12:34 UTC, closed without merging