Feat : Added a feature for users to add feadback on github
commons-app/apps-android-commons pull request #5578
Opened 2024-02-29 18:47 UTC by neeldoshii

## Description

* Fixes #5563 

## Approach
It gives the users an ability to place feedbacks (issues, new feature) directly on the github from the app.

## Testing Instructions
1. Open the More Menu from Bottom Navigation.
2. Bottom Sheet will be opened.
3. From the Bottom Sheet click on Send Feedback on Github
4. Browser will open (github issue section)

## Screenshots/ Working Video

https://github.com/commons-app/apps-android-commons/assets/60827173/f60d2287-db80-4cb0-b49b-ddb37eb0ea1d

## Tests performed 

Test performed on Google Pixel 4 (Emulator).

Feel free to place your opinion.

2024-03-01 16:23 UTC, shashankiitbhu requested changes
Review by student

Before:

https://github.com/commons-app/apps-android-commons/assets/126143257/b780ae00-953f-4fef-a7cc-06bb40433a0c

After:

https://github.com/commons-app/apps-android-commons/assets/126143257/5b87f8b2-f62a-44d3-86dc-c9703d0c60e3

Mentioned Issue is Solved

2024-03-01 16:23 UTC, shashankiitbhu commented on app/src/main/java/fr/free/nrw/commons/navtab/MoreBottomSheetFragment.java
> +        final String url = "https://github.com/commons-app/apps-android-commons/issues";
can you make this a string constant?

2024-03-02 13:06 UTC, neeldoshii commented on app/src/main/java/fr/free/nrw/commons/navtab/MoreBottomSheetFragment.java
> +        final String url = "https://github.com/commons-app/apps-android-commons/issues";
fixed. Thanks for the feedback.

2024-03-09 19:28 UTC, shashankiitbhu approved these changes

2024-04-01 08:36 UTC, nicolas-raoul approved these changes
Thanks! :-)

2024-04-01 08:36 UTC, merged

2024-04-09 01:07 UTC, ShashwatKedia commented
@nicolas-raoul Sorry to ping after the PR has been merged, but this PR has two test cases failing [here](https://github.com/commons-app/apps-android-commons/actions/runs/8505891388/job/23295149636):

`fr.free.nrw.commons.description.DescriptionEditActivityUnitTest > testUpdateDescription FAILED
    java.lang.reflect.InvocationTargetException at DescriptionEditActivityUnitTest.kt:120
        Caused by: fr.free.nrw.commons.auth.csrf.InvalidLoginTokenException at DescriptionEditActivityUnitTest.kt:120`

`fr.free.nrw.commons.description.DescriptionEditActivityUnitTest > testOnSubmitButtonClicked FAILED
    java.lang.reflect.InvocationTargetException at DescriptionEditActivityUnitTest.kt:132
        Caused by: fr.free.nrw.commons.auth.csrf.InvalidLoginTokenException at DescriptionEditActivityUnitTest.kt:132`
        
This is causing the tests to fail on all other PRs. Also, while I was testing the main branch, I was surprised to see that this PR was merged, when there was still some discussion going on [here](https://github.com/commons-app/apps-android-commons/issues/5563#issuecomment-1974803819) about the best possible UI for feedback on GitHub. And as mentioned there, even you didn't approve of the concept of having 2 separate menu items.

2024-04-09 10:55 UTC, nicolas-raoul commented
Thanks @ShashwatKedia for pointing this out!
Actually, even after I revert 54312fc2ac1bc88b03539c7627e6267a49f79b9d these tests fail.
Maybe an earlier commit? git bisect would help here.

I agree two menu items is not ideal, but I felt that it was still better than nothing.

2024-04-09 14:04 UTC, nicolas-raoul commented
git bisect says 3d1efecb55c931ffe55137bff7e69671ef5cada8 is the first commit where unit tests start failing.

2024-04-09 14:14 UTC, ShashwatKedia commented
Oh, thanks and sorry, @nicolas-raoul, that you had to perform git bisect for this. I'll look into this and try to perform the actions required by PR without failing the tests

2024-04-09 14:15 UTC, ShashwatKedia commented
> I agree two menu items is not ideal, but I felt that it was still better than nothing.

Um, what do you think about the solution proposed [here](https://github.com/commons-app/apps-android-commons/issues/5563#issuecomment-1975746623) ?