Improved UX for Nearby Export
commons-app/apps-android-commons pull request #5654
Opened 2024-03-25 15:48 UTC by kanahia1

**Description (required)**

What changes did you make and why?

**Tests performed (required)**

Tested prodDebug on Samsung S21 FE with API level 33.

**Screenshots (for UI changes only)**

https://github.com/commons-app/apps-android-commons/assets/114223204/c8c5636b-1874-46de-8a9f-7ee24c4ac289

2024-03-27 03:46 UTC, nicolas-raoul requested changes
Great improvement!
Just a minor correction for internationalization needed and I will merge.

2024-03-27 03:46 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java
> +                    progressDialog.setTitle("Saving KML File");
Would you mind internationalizing this string too?

2024-03-27 03:46 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java
> +                    progressDialog.setTitle("Saving GPX File");
Would you mind internationalizing this string too?

2024-03-27 16:05 UTC, kanahia1 commented
@nicolas-raoul, Sorry for the delay. I have fixed issue in the newer commit https://github.com/commons-app/apps-android-commons/pull/5654/commits/3c864d826b662a8e4500e18e1502058a3a075d06

2024-03-28 14:12 UTC, nicolas-raoul approved these changes

2024-03-28 14:12 UTC, merged