Fixed Issue #5619: Add label "Congratulations, all pictures in this album have been either uploaded or marked as not for upload
commons-app/apps-android-commons pull request #5696
Opened 2024-04-18 13:34 UTC by Thejas775

**Description (required)**

Fixes #5619 

What changes did you make and why?
Added label "Congratulations, all pictures in this album have been either uploaded or marked as not for upload" whenever user switches off the selectorSwitch.

2024-04-18 13:43 UTC, nicolas-raoul commented
Here is a useful link to find unassigned bugs:

https://github.com/commons-app/apps-android-commons/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+-label%3Adebated+label%3Abug+-label%3A%22low+priority%22

:-)

2024-04-20 11:29 UTC, Thejas775 commented
> Here is a useful link to find unassigned bugs:
> 
> https://github.com/commons-app/apps-android-commons/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+-label%3Adebated+label%3Abug+-label%3A%22low+priority%22
> 
> :-)

Sir is this issue resolved by this ?

2024-04-29 09:30 UTC, nicolas-raoul requested changes
Any idea why the text is not displayed here? Thanks! 🙂

https://github.com/commons-app/apps-android-commons/assets/99590/6644bb5d-334c-4a24-b82c-ab95445fe9f5

2024-04-29 18:31 UTC, Thejas775 commented
> Any idea why the text is not displayed here? Thanks! 🙂
> 
>  1000044741.mp4

Will check on it sir !

2024-05-02 14:26 UTC, Thejas775 commented
@nicolas-raoul 
![Screenshot from 2024-05-02 19-53-42](https://github.com/commons-app/apps-android-commons/assets/58774753/2da4f586-e6fd-4efe-9238-a25b16d33db6)
SIr earlier I thought the images.notempty will do the work. But now it seems the images are of total device and the filetered images is of the the particular folder. I tried using the 
`        notForUploadStatusDao.getNotForUploadFromImageSHA1(image.id.toString()) == null
`
But it didnt work if you could point me to where from can i get the status of images which are marked as not for upload.

Thanks.

2024-08-26 06:53 UTC, nicolas-raoul commented
Sorry for the delay!
I don't think that using the DAO is needed.
I believe that checking whether the message should be displayed or not can be done on the UI side.

2024-09-05 12:02 UTC, Thejas775 commented
> Sorry for the delay! I don't think that using the DAO is needed. I believe that checking whether the message should be displayed or not can be done on the UI side.

okay sir will try

2025-01-24 11:24 UTC, nicolas-raoul commented
I believe this was finished in https://github.com/commons-app/apps-android-commons/pull/6095 🙂

2025-01-24 11:25 UTC, closed without merging