Added Wikitalk Page
commons-app/apps-android-commons pull request #5740
Opened 2024-05-23 14:47 UTC by kanahia1

**Description (required)**

Fixes #2425

What changes did you make and why?

**Tests performed (required)**

Tested prodDebug on Samsung S21 FE with API level 33.

**Progress**

- Improved BottomSheet in the Nearby for the Lanscape Mode

https://github.com/commons-app/apps-android-commons/assets/114223204/b2009460-35f0-41de-8f45-0c18614e20ae
	

- Added Wikitalk page

![WhatsApp Image 2024-05-23 at 20 17 11_342c1e41](https://github.com/commons-app/apps-android-commons/assets/114223204/79be34ed-1fa6-48d5-9b4e-9a80187b135d)

---

Keeping this PR as draft until I am able to solve the problem for creating/editing page.

2024-05-24 00:23 UTC, nicolas-raoul commented
The UI looks good to me so far. 🙂

2024-05-30 08:08 UTC, kanahia1 commented
Finally I am successful in creating pages 

![WhatsApp Image 2024-05-30 at 13 35 32_464bb46e](https://github.com/commons-app/apps-android-commons/assets/114223204/876c3fa3-07d0-498d-93ea-f26b768f1006)

https://commons.m.wikimedia.org/wiki/Talk:Q65994945

Since we can also add subject, Should we also add option for the subject? Currently I am taking only description as input (e.g This is demo text) and subject is hardcoded (e.g For Testing Purpose)

2024-05-30 08:34 UTC, nicolas-raoul commented
For the title I would suggest a hard-coded English-language-only `==Please fix this item==`.

The body of the message could be something like:

```
Someone using the [[Commons:Mobile_app|Commons Android app]] went to this item's geographical location (123.43124,98.97789) and noted the following problem(s):
* <nowiki>_Is at a different place._</nowiki>

Details: <nowiki>_It has moved to across the street blabla._</nowiki>

Please anyone fix the item accordingly, then reply to mark this section as fixed. Thanks a lot for your cooperation!

~~~~
```

Indicating the current location of the item is useful because it may change in the future, making it difficult to understand what is being talked about (for instance what is the initial side of the street).

2024-05-31 07:19 UTC, kanahia1 commented
Hello @nicolas-raoul, I have successfully created the wikitalk page and here is design I have came up with for the page https://commons.m.wikimedia.org/wiki/Talk:Q73763141 (created/edited using the app)

![WhatsApp Image 2024-05-31 at 12 45 53_82f0a294](https://github.com/commons-app/apps-android-commons/assets/114223204/c3bacf11-bbe4-4b73-8bac-0b77bcda715a)

I am looking for more suggestions for the design

2024-05-31 07:58 UTC, nicolas-raoul commented
Sorry my mistake please put the italics outside of the nowiki tags not inside.

The tildes signature was not recognized it seems. Not a big issue.

2024-05-31 08:09 UTC, nicolas-raoul commented
Would you mind posting a screencast showing the whole use of the feature as implemented now?

2024-05-31 11:33 UTC, nicolas-raoul commented
I think that **checkboxes** like in the issue description would lead to more helpful feedback:

```
Write something about the "GS1 Japan" item. It will be publicly visible. 

☐ "GS1 Japan" does not exist anymore, no picture can ever be taken of it. 
☑ "GS1 Japan" is at a different place (please specify the correct place below, if possible tell us the correct latitude/longitude). 
☐ Other problem or information (please explain below).

 --------------------------------------------------------------
 blabla
 -------------------------------------------------------------- 
```

Current talk page content would come after this.
Actually, showing talk page content in the app itself is not required (and impossible to do perfectly due to complex wikicode such as transclusions), a web link to the talk page is enough. 🙂

2024-05-31 11:37 UTC, nicolas-raoul commented
The section posted to the talk page would include the English text for each selected checkbox, plus the comment if there is one.

2024-05-31 11:42 UTC, kanahia1 commented
Got it 😄 Will share the commit asap

2024-06-01 02:41 UTC, kanahia1 commented
Hello @nicolas-raoul, I have implemented new page. And here's video demonstration

https://github.com/commons-app/apps-android-commons/assets/114223204/75d18ebf-d860-4e10-b0eb-b51b4f233dbc

2024-06-01 03:38 UTC, nicolas-raoul commented
Looks great!
I am getting a crash though, screencast on Zulip.

2024-06-01 05:09 UTC, nicolas-raoul commented
Great but I noticed an issue: The server to edit is Wikidata server, not Commons server. 🙂

2024-06-01 05:13 UTC, nicolas-raoul commented
For instance, your Abaspura edit should be made here:
https://www.wikidata.org/w/index.php?title=Talk:Q4663549&action=edit&redlink=1
not at https://commons.wikimedia.org/wiki/Talk:Q4663549 which is not the talk page of a real item or anything on that wiki.

2024-06-01 06:19 UTC, RitikaPahwa4444 reviewed
Nice! The last option, that is, "Other problem or information (please explain below)" has an edit text field but I'm able to send the talk without any comment. How about making it mandatory?

2024-06-01 06:36 UTC, nicolas-raoul commented
+1 on making the text field mandatory if the third checkbox is enabled.

By the way, it looks like a bookmark is set to any item I open the dialog for. Is that intended? Screencast on Zulip.

2024-06-01 07:27 UTC, kanahia1 commented
Also I have changed the url now the edit is made a wikidata url 🎉
https://m.wikidata.org/wiki/Talk:Q16640641

2024-06-03 05:52 UTC, nicolas-raoul commented
Working great, thanks! https://www.wikidata.org/wiki/Talk:Q65225721
How about coming back after the Wikidata edit is made, rather than staying on the "Write something about the [...] item" activity? Otherwise people may not see the toast, and post twice.

2024-06-03 06:00 UTC, nicolas-raoul requested changes
Great work, a bit of polishing still needed before merging. :-)

2024-06-03 06:00 UTC, nicolas-raoul commented on app/src/main/res/values/strings.xml
> +  <string name="nearby_wikitalk">wikitalk</string>
This is the tooltip right? How about "Report a problem about this item to Wikidata"?

2024-07-08 01:32 UTC, kanahia1 commented
@nicolas-raoul, I am sorry I totally forgot about the reviews. I have made all the suggested changes in the newer commit  https://github.com/commons-app/apps-android-commons/pull/5740/commits/c0b2fc7a5cb5a32d25aed4d3c9d5b9c0d23a3d79

2024-07-08 06:13 UTC, nicolas-raoul approved these changes
Fantastic, thanks a lot for taking care of this! 🙂

2024-07-08 06:13 UTC, merged