Fixes Issue #5832: Navigation Banner Appears in Media Details Screen
commons-app/apps-android-commons pull request #5839
Opened 2024-09-28 00:21 UTC by Jason-Whitmore

**Description (required)**

Fixes #5832 

What changes did you make and why?

There were two changes made.

First, a helper method was created to easily retrieve the ContributionsFragment. Accessing the ContributionsFragment is required to hide the navigation banner.

(One concern I have with this helper method is that it attempts to find the ContributionsFragment by looping through the parent fragments repeatedly in a while loop. The advantage of this strategy is that it can retrieve the ContributionsFragment anywhere in the Fragment parent-child structure if it exists. The primary disadvantage is that if the Fragment parent-child structure is a loop with no ContributionsFragment, then the while loop will never terminate.

I can rewrite this method to retrieve the ContributionsFragment directly (using two calls to getParentFragment()), but this strategy is less flexible. **Should I rewrite this helper method to not use a while loop or is the current implementation okay?**)

Second, old code which attempted to hide the navigation banner (but was unsuccessful) was replaced with a call to the helper method and then checking for null objects. If the objects are not null, then the navigation banner is successfully hidden.

**Tests performed (required)**

Tested betaDebug on Android Studio Emulator with API level 34.

**Screenshots (for UI changes only)**

[issue_5832_compressed.webm](https://github.com/user-attachments/assets/1ad66a66-1684-46a0-8c7c-ac66ca0980da)

In this video, the navigation banner is visible from the contributions menu. When a specific contribution is selected, the navigation banner is hidden. Once the back button is pressed, the contributions menu appears with the navigation banner visible again.

2024-09-28 13:14 UTC, nicolas-raoul commented
I guess the loop will at least terminate when there is no parent, so I don't worry about infinite loop here.

2024-09-28 13:24 UTC, nicolas-raoul requested changes

2024-09-28 13:24 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java
> +        ContributionsFragment cf = this.getContributionsFragmentParent();
In Java we prefer explicit variable names, even if long. So unless there is a reason I missed, would you mind renaming `cf` to `contributionFragment`?

2024-09-28 13:24 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java
> +        Fragment f = this;
Similarly, `f` to `fragment`.

2024-09-28 13:24 UTC, nicolas-raoul commented on app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java
> +        if(cf != null && cf.binding != null){
Sorry for nitpicking, but would you mind inserting a space character before `if` and `while`, here and below?

2024-09-28 14:15 UTC, nicolas-raoul commented
Before:

https://github.com/user-attachments/assets/a6c39aca-5406-4e98-8338-18ed3800ff78

After:

https://github.com/user-attachments/assets/2de4318c-3a05-43d1-81ef-7265a6da47a5

2024-09-28 14:18 UTC, nicolas-raoul commented
@rohit9625 If you have time, would you mind seeing whether this PR fixes the issue? As seen in my previous post above, for me both before and after are fast enough haha.

2024-09-28 14:59 UTC, rohit9625 commented
> @rohit9625 If you have time, would you mind seeing whether this PR fixes the issue? As seen in my previous post above, for me both before and after are fast enough haha.

I'm looking into it :》

2024-09-29 10:29 UTC, rohit9625 commented
It's still the same behavior on my device. Did you reproduce the issue before fixing it @Jason-Whitmore?

2024-09-30 17:38 UTC, rohit9625 commented
https://github.com/user-attachments/assets/57d1aee2-c18c-4d72-9181-0d7b72958279

**Explanation:-**

The **Nearby Banner** was still present even after opening `MediaDetailsFragment`. However, it disappeared after some time but not in the second case.
I observed that it only hides when the value of the distance updates. You can see when I clicked the contribution the very first time, the value of **293m**, and when I changed my location, it was updated to **294m** and hence, removed from the screen. However, on the second try, I didn't change my location so that value remained the same, and as a result, the banner did not hide.

I just realized @nicolas-raoul that `Nearby Banner` was not showing on your screen-cast even on the contributions list. Please check on that :)

2024-10-01 06:43 UTC, nicolas-raoul commented
@rohit9625 Ah thanks for pointing this out, I can replicate on main now. 🙂 I am out so I cannot test the PR now.

2024-10-01 08:05 UTC, rohit9625 commented
No problem @nicolas-raoul :)
Could you please look for a fix @Jason-Whitmore ?

2024-10-02 04:52 UTC, Jason-Whitmore commented
Thank you all for the large discussion here. I'll try and address what I can.

When I was developing the changes in this pull request, I was working on betaDebug. I had reproduced *most* of the issue there (on main), but the navigation banner never disappeared at all (rather than disappearing after a few seconds). Once the changes had been made, it appeared the bug was fixed. I assumed that fixing the bug on betaDebug would fix it on prodDebug. I did not test these changes directly on prodDebug before I submitted this pull request. I apologize.

Just now I tested these changes on prodDebug and the bug appears fixed for me. However, I only have one contribution uploaded for my testing, rather than the 8 that @rohit9625 has in the most recent video. **Could the number of contributions have some kind of effect on whether or not the bug appears?**

Thanks again for all the feedback. I'll keep working on this.

2024-10-08 01:56 UTC, Jason-Whitmore commented
After further debugging, I do not believe that the number of contributions is related to whether or not this bug appears.

On the main branch, I can confirm (as @rohit9625 says) that moving the device's GPS location causes the navigation banner to hide when looking at the media details. The bug is more difficult to reproduce on the Android Studio emulator, which I had been exclusively using until recently. The bug is easier to reproduce using a physical device.

On this branch (issue_5832), the bug appears to be fixed both on the Android Studio emulator and on my physical device. I've tried to reproduce the bug on this branch (prodDebug build), using both the Debug and Run options within Android Studio and the bug still appears to be fixed. Information about my Android Studio emulator and physical device is below:

Emulator:
-Pixel 3a
-Android 14
-API 34 extension level 7
-x86_64

Physical device:
-Nokia 6.2
-Android 11
-API 30 extension level 11
-arm64

Other than differences in devices, I'm not sure what else could be causing the bug to appear fixed for me and unfixed for anyone else. Any suggestions or advice would be appreciated.

2025-01-11 03:16 UTC, closed without merging