Issue 1 launguage order backend queries
commons-app/apps-android-commons pull request #5889
Opened 2024-10-24 12:55 UTC by Adeeth101

**Languages order preference UI and functionality enhancement.**

Fixes #5826

What changes did you make and why?

Gradle Files: 
Some fo the gradle code was outdated and didn't work on our latest emulators. I had to remove code that was no longer supported.

Preferences.XML: 
Added a new preference category in the preferences UI for secondary language picking
Prefs.java was also changed to hold a serialised string of secondary language codes

Strings.XML: 
Added new strings that represent additions in UI

SettingsFragments: 
- Had to accommodate new preference in OnCreate
- Made a new dialog called prepareSecondaryLanguageDialog(). 
- Made helper methods for that dialog that use a new language adapter SavedLanguagesAdapter
- modified saving and getting key value methods to accommodate the new category in Prefs

NearbyController and NearbyPlaces:
Injected the KV store into the controller and passed the serialised string as a new argument to the json API client in NearbyPlaces

OkHttpJsonApiClient:
changed the getPlaces method to make use of the new parameter (the serialised language code)
made stringbuilders to automatically generate further SparQL queries based on the serialised code list
(Also modified the SparQL file itself to add placeholders for the additional strings created by the method)

**Tests performed (required)**
Apart from extensive manual software testing, the following unit tests were created:
StringBuilderTest.java
SettingsFragmentSecondaryLanguageTests.kt

Tested {build variant, e.g. ProdDebug} on {name of device or emulator} with API level {API level}.

**Screenshots (for UI changes only)**
![image](https://github.com/user-attachments/assets/2846e1a9-a2bb-437b-90d9-338dcdb254d5)
![image](https://github.com/user-attachments/assets/792500be-5544-4374-a94b-b8441e06d901)

Need help? See https://support.google.com/android/answer/9075928

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

2024-10-25 00:23 UTC, nicolas-raoul requested changes
Thanks a lot!

Sorry I am outside and can't test right now.

Would you mind describing how I should do to switch German (de) and Japanese (ja)?

Any specific reason to split primary and secondary, rather than having just one list of languages? It is fine but just curious what your thoughts are om this.

2024-10-25 06:52 UTC, Adeeth101 commented
Ill work on name changes and the change in the res file is unintentional sorry about that...

2024-10-25 06:59 UTC, Adeeth101 commented on app/src/main/res/values/arrays.xml
> +    <array name="default_languages">
That wass a mistake, apologies.

2024-10-25 07:01 UTC, Adeeth101 commented on app/src/main/res/layout/dialog_select_secondary_language.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
I could look into that but would that be something that is absolutely needed for the PR?

2024-10-25 07:01 UTC, Adeeth101 commented on app/src/main/java/fr/free/nrw/commons/settings/SettingsFragment.java
> +    private void prepareSecondaryLanguageDialog() {
Ill do that for the rest of the plural cases.

2024-10-25 13:30 UTC, nicolas-raoul commented on app/src/main/res/layout/dialog_select_secondary_language.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
Not absolutely needed, please just create a new enhancement issue about it if you don't have time to do it. Thanks! :-)

2024-10-25 13:31 UTC, nicolas-raoul commented
Also, please rebase or merge from master. Thanks! :-)

2024-10-27 04:46 UTC, Adeeth101 commented
@nicolas-raoul Ive squashed merge conflicts and resolved above points.

2024-11-15 09:48 UTC, nicolas-raoul commented
I am so sorry for leaving it for so long, would you mind this other conflict? Thanks a lot!

2024-11-16 05:09 UTC, Adeeth101 commented
Ill look into it

2024-12-20 04:53 UTC, Adeeth101 commented
@nicolas-raoul Sorry again for being late. Ill fix it today.

2024-12-20 17:52 UTC, Adith101 commented
Hi @nicolas-raoul this is (@Adeeth101) im on my alt account because I'm on my phone. 

A lot of the java classes I edited are now deleted and replaced kotlin versions. Not a huge deal but it does mean I basically cant auto merge and it will take some time to redo my work in kotlin. Give me another day please and thanks for the patience.

2024-12-21 13:10 UTC, closed without merging

2024-12-21 13:10 UTC, Adeeth101 commented
I made a new MR, which should now be good for the updated Kotlin version of the app.