5661 statistics to badges
commons-app/apps-android-commons pull request #5917
Opened 2024-11-01 02:39 UTC by YujingZHG

**Description (required)**

Fixes #5661 

What changes did you make and why?

Transformed the statistics of achievement into badges. Each badge changes to gray and hides its count if the value is 0. 

- Added badgeRender(Map<ImageView, TextView> badgeMap) function, used to render badges with a filter, and the GrayFilter(ImageView imageView) function applies the gray filter. 

- Used Google’s FlexboxLayout to enable badges to wrap automatically in the layout.

- Added String Badges in Strings.xml, drawable badge_number_background.xml in drawable for displaying.

**Tests performed (required)**

Tested AchievementsFragmentUnitTests on Medium Phone API 33 (Android 13.0 "Tiramisu" | arm64 emulator).

**Screenshots (for UI changes only)**
Set badges numbers to 0
<img width="271" alt="image" src="https://github.com/user-attachments/assets/703ac7f5-0622-4b0b-be55-ac2797267f79">
None 0 badges
<img width="280" alt="image" src="https://github.com/user-attachments/assets/9fe1b644-a271-49ca-bbd4-4e44a27760c0">

---

- [x] I've read CONTRIBUTING.md

2024-11-01 03:45 UTC, nicolas-raoul commented
Looks great! :-)

2024-11-02 04:34 UTC, YujingZHG commented
Hi  @nicolas-raoul what should I do with the failing check? or just leave it there?

2024-11-04 01:48 UTC, nicolas-raoul requested changes
I just tested, it is generally great, I only found these issues:

- Tapping the "featured images" icon shows the "thanks received" tooltip.
- Tapping the "quality images" icon shows the "featured images" tooltip.
- I am pretty sure I have 100+ nearby uploads and zero featured images, but I see this:
![Screenshot_20241104-101610~2.png](https://github.com/user-attachments/assets/bd34153d-1327-4e1c-be26-95312f645d30)

If the count was already incorrect in the main branch, then no need to fix the count.

2024-11-04 02:57 UTC, nicolas-raoul commented on app/src/main/res/values/strings.xml
> +  <string name="statistics">Badges</string>
Can this one be removed?

2024-11-04 02:58 UTC, nicolas-raoul commented
I will check whether unit tests fail in master. If yes then don't worry.

2024-11-12 14:17 UTC, nicolas-raoul commented
Please do not worry about unit tests, this is tracked at #5921

But do you have time to check https://github.com/commons-app/apps-android-commons/pull/5917#pullrequestreview-2412011916 ? :-)

2024-11-21 12:46 UTC, nicolas-raoul commented
@YujingZHG Did you get a chance to check? A small conflict must also be fixed. Is it OK for someone else to continue your work? Thanks! :-)

2024-11-21 12:52 UTC, YujingZHG commented
@nicolas-raoul  Yes. Thanks :)

2024-12-07 01:12 UTC, closed without merging

2024-12-07 01:12 UTC, nicolas-raoul commented
Thanks all! :-)